import type { Lesson } from './types'

export const presentTenseVerbPatternsLesson: Lesson = {
  id: 'present-tense-verb-patterns',
  trackId: 'core-grammar',
  topics: ['present', 'verbs', 'routine'],
  level: 'A1-A2',
  title: 'Present Tense Verb Patterns',
  subtitle: 'Learn five clear verb families, compare them in tables, and drill them through generated exercises.',
  summary:
    'This rewrite reorganizes the Hungarian present tense into five learner-friendly verb groups plus the irregular anchors van, megy, and jön. The lesson now uses structured tables for quick comparison and generator-based exercises for pattern choice, transform, cloze, ordering, vocabulary review, and adaptive practice.',
  sourceUnits: ['Present tense reference sheet', 'Verb summary table'],
  goals: [
    'Recognize the five core present-tense verb families without mixing them together.',
    'Use quick tables to compare endings before you move into sentence-level practice.',
    'Produce correct present-tense forms in short everyday scenes instead of memorizing endings in isolation.',
    'Treat van, megy, and jön as whole irregular anchor families.',
  ],
  studyFlow: [
    'Read one table at a time and say the six-person family aloud before you start the exercises.',
    'Use the pattern drills first, then switch to cloze and sentence-builder practice to test the same forms in context.',
    'Keep one base verb per family as your anchor: fut, olvas, eszik, lakik, takarít.',
    'When a form has more than one learner-level variant, pick one for active use and simply recognize the alternative.',
    'Come back to the simplified chart after each round and check whether the confusing ending now feels predictable.',
  ],
  explanations: [
    {
      title: 'Start with one tense system',
      body:
        'Stay in the indefinite present first. The goal here is not every possible Hungarian verb ending at once, but a stable map: five groups, one simplified chart, and three irregular anchors that you can reuse in everyday sentences.',
      tips: [
        'Say the person and the form together first: én futok, te futsz, ő fut.',
        'Move from table review into short scene practice as quickly as possible.',
      ],
      tables: [
        {
          title: 'Verb groups overview',
          columns: ['Group', 'Verb type', 'Examples', 'Key pattern'],
          rows: [
            ['1', 'Short consonant-ending verbs', 'fut, áll, ül', 'Simple endings'],
            ['2', '-vas / -vez / -z / -sz style verbs', 'olvas, főz, néz', 'te often gets -ol / -el'],
            ['3', 'Special -ik eating / drinking type', 'eszik, iszik', 'Special én / te / ők forms'],
            ['4', 'Regular -ik verbs', 'lakik, játszik, alszik', 'ő keeps -ik'],
            ['5', '-ít or dense stem type', 'takarít, fest', 'Regular shape with linking vowels'],
          ],
        },
        {
          title: 'Main conjugation pattern table',
          columns: [
            'Person',
            '1. fut / áll / ül',
            '2. olvas / főz / néz',
            '3. eszik / iszik',
            '4. lakik',
            '5. takarít / fest',
          ],
          rows: [
            ['én', '-ok / -ek / -ök', '-ok / -ek / -ök', '-em / -om', '-om / -ok', '-ok / -ek'],
            ['te', '-sz', '-ol / -el', '-el / -ol', '-sz', '-asz / -esz / -sz'],
            ['ő / ön', 'base verb', 'base verb', '-ik', '-ik', 'base verb'],
            ['mi', '-unk / -ünk', '-unk / -ünk', '-ünk / -unk', '-unk / -ünk', '-unk / -ünk'],
            [
              'ti',
              '-tok / -tek / -tök',
              '-tok / -tek / -tök',
              '-tek / -tok',
              '-tok / -tek / -tök',
              '-tok / -tek / -tök / -otok / -etek',
            ],
            [
              'ők / önök',
              '-nak / -nek',
              '-nak / -nek',
              '-nek / -nak',
              '-nak / -nek',
              '-anak / -enek / -nak / -nek',
            ],
          ],
        },
      ],
    },
    {
      title: 'Group 1 and 2: simple stems and s-stems',
      body:
        'Group 1 stays close to the bare stem, while Group 2 looks similar but often changes shape most clearly in the te and ti forms. These are the first two tables to overlearn because they cover many daily verbs.',
      tips: [
        'For Group 2, the te form is often the easiest place to spot the family: olvasol, nézel, főzöl.',
        'Read the whole row once, then test yourself down the person column.',
      ],
      tables: [
        {
          title: '1) fut type',
          columns: ['Person', 'Ending', 'Example with fut'],
          rows: [
            ['én', '-ok / -ek / -ök', 'futok'],
            ['te', '-sz', 'futsz'],
            ['ő', 'base', 'fut'],
            ['mi', '-unk / -ünk', 'futunk'],
            ['ti', '-tok / -tek / -tök', 'futtok'],
            ['ők', '-nak / -nek', 'futnak'],
          ],
        },
        {
          title: 'Quick check: ül',
          columns: ['Person', 'Form'],
          rows: [
            ['én', 'ülök'],
            ['te', 'ülsz'],
            ['ő', 'ül'],
            ['mi', 'ülünk'],
            ['ti', 'ültök'],
            ['ők', 'ülnek'],
          ],
          compact: true,
        },
        {
          title: '2) olvas / főz / néz type',
          columns: ['Person', 'Ending', 'Example with olvas'],
          rows: [
            ['én', '-ok', 'olvasok'],
            ['te', '-ol', 'olvasol'],
            ['ő', 'base', 'olvas'],
            ['mi', '-unk', 'olvasunk'],
            ['ti', '-tok', 'olvastok'],
            ['ők', '-nak', 'olvasnak'],
          ],
        },
        {
          title: 'Quick check: néz',
          columns: ['Person', 'Form'],
          rows: [
            ['én', 'nézek'],
            ['te', 'nézel'],
            ['ő', 'néz'],
            ['mi', 'nézünk'],
            ['ti', 'néztek'],
            ['ők', 'néznek'],
          ],
          compact: true,
        },
        {
          title: 'Quick check: főz',
          columns: ['Person', 'Form'],
          rows: [
            ['én', 'főzök'],
            ['te', 'főzöl'],
            ['ő', 'főz'],
            ['mi', 'főzünk'],
            ['ti', 'főztök'],
            ['ők', 'főznek'],
          ],
          compact: true,
        },
      ],
    },
    {
      title: 'Group 3 and 4: the two -ik systems',
      body:
        'Do not treat all -ik verbs as one group. Eszik and iszik follow the special eating / drinking pattern, while lakik-type verbs keep -ik in the third person but can vary more in the learner forms you meet across textbooks.',
      tips: [
        'Keep eszem / iszom separate from lakom / lakok style forms.',
        'For regular -ik verbs, use the exact study form your course expects and recognize the common alternative if needed.',
      ],
      tables: [
        {
          title: '3) eszik / iszik type',
          columns: ['Person', 'Ending', 'Example with eszik', 'Example with iszik'],
          rows: [
            ['én', '-em / -om', 'eszem', 'iszom'],
            ['te', '-el / -ol', 'eszel', 'iszol'],
            ['ő', '-ik', 'eszik', 'iszik'],
            ['mi', '-ünk / -unk', 'eszünk', 'iszunk'],
            ['ti', '-tek / -tok', 'esztek', 'isztok'],
            ['ők', '-nek / -nak', 'esznek', 'isznak'],
          ],
        },
        {
          title: '4) lakik type',
          columns: ['Person', 'Ending', 'Example with lakik'],
          rows: [
            ['én', '-om / -ok', 'lakom / lakok'],
            ['te', '-sz', 'laksz'],
            ['ő', '-ik', 'lakik'],
            ['mi', '-unk', 'lakunk'],
            ['ti', '-tok', 'laktok'],
            ['ők', '-nak', 'laknak'],
          ],
        },
        {
          title: 'Quick check: játszik',
          columns: ['Person', 'Form'],
          rows: [
            ['én', 'játszom / játszok'],
            ['te', 'játszol'],
            ['ő', 'játszik'],
            ['mi', 'játszunk'],
            ['ti', 'játszotok'],
            ['ők', 'játszanak'],
          ],
          compact: true,
        },
        {
          title: 'Quick check: fürdik',
          columns: ['Person', 'Form'],
          rows: [
            ['én', 'fürdöm / fürdök'],
            ['te', 'fürdesz'],
            ['ő', 'fürdik'],
            ['mi', 'fürdünk'],
            ['ti', 'fürödtök / fürdetek'],
            ['ők', 'fürdenek'],
          ],
          note: 'The ti form is often simplified differently depending on course level, so keep one classroom version active and recognize the other.',
          compact: true,
        },
      ],
    },
    {
      title: 'Group 5 and the irregular anchors',
      body:
        'Group 5 is still learnable as a pattern, but the stem often feels heavier, so full sound chunks help more than abstract endings. Van, megy, and jön should simply be memorized as complete families.',
      tips: [
        'Say megyek, mész, megy together as one package.',
        'Treat jövök and jöttök as anchor forms instead of trying to predict them from a simple rule.',
      ],
      tables: [
        {
          title: '5) takarít / fest type',
          columns: ['Person', 'Ending', 'Example with takarít', 'Example with fest'],
          rows: [
            ['én', '-ok / -ek', 'takarítok', 'festek'],
            ['te', '-asz / -esz', 'takarítasz', 'festesz'],
            ['ő', 'base', 'takarít', 'fest'],
            ['mi', '-unk / -ünk', 'takarítunk', 'festünk'],
            ['ti', '-otok / -etek / -tök', 'takarítotok', 'festetek'],
            ['ők', '-anak / -enek', 'takarítanak', 'festenek'],
          ],
        },
        {
          title: 'VAN = to be',
          columns: ['Person', 'Form'],
          rows: [
            ['én', 'vagyok'],
            ['te', 'vagy'],
            ['ő', 'van'],
            ['mi', 'vagyunk'],
            ['ti', 'vagytok'],
            ['ők', 'vannak'],
          ],
          compact: true,
        },
        {
          title: 'MEGY = to go',
          columns: ['Person', 'Form'],
          rows: [
            ['én', 'megyek'],
            ['te', 'mész'],
            ['ő', 'megy'],
            ['mi', 'megyünk'],
            ['ti', 'mentek'],
            ['ők', 'mennek'],
          ],
          compact: true,
        },
        {
          title: 'JÖN = to come',
          columns: ['Person', 'Form'],
          rows: [
            ['én', 'jövök'],
            ['te', 'jössz'],
            ['ő', 'jön'],
            ['mi', 'jövünk'],
            ['ti', 'jöttök'],
            ['ők', 'jönnek'],
          ],
          compact: true,
        },
      ],
    },
    {
      title: 'Super simplified review chart',
      body:
        'Use this when you need a quick reset before practice. It is intentionally compressed, so its job is not to explain every detail but to help you remember which family you are in before you answer.',
      tips: [
        'If a form feels strange, check first whether it belongs to Group 3, Group 4, or one of the irregular anchors.',
        'Read the copy-friendly table horizontally to compare one group and vertically to compare one person.',
      ],
      tables: [
        {
          title: 'Super simplified ending chart',
          columns: ['Person', 'Most common endings'],
          rows: [
            ['én', '-ok / -ek / -ök / -om / -em'],
            ['te', '-sz / -ol / -el / -asz / -esz'],
            ['ő', 'base verb / -ik'],
            ['mi', '-unk / -ünk'],
            ['ti', '-tok / -tek / -tök'],
            ['ők', '-nak / -nek / -anak / -enek'],
          ],
        },
        {
          title: 'Copy-friendly study table',
          columns: ['Group', 'én', 'te', 'ő', 'mi', 'ti', 'ők'],
          rows: [
            ['1) fut / áll / ül', '-ok / -ek / -ök', '-sz', 'base', '-unk / -ünk', '-tok / -tek / -tök', '-nak / -nek'],
            ['2) olvas / főz / néz', '-ok / -ek / -ök', '-ol / -el', 'base', '-unk / -ünk', '-tok / -tek / -tök', '-nak / -nek'],
            ['3) eszik / iszik', '-em / -om', '-el / -ol', '-ik', '-ünk / -unk', '-tek / -tok', '-nek / -nak'],
            ['4) lakik', '-om / -ok', '-sz', '-ik', '-unk / -ünk', '-tok / -tek / -tök', '-nak / -nek'],
            ['5) takarít / fest', '-ok / -ek', '-asz / -esz', 'base', '-unk / -ünk', '-tok / -tek / -tök / -otok / -etek', '-anak / -enek'],
          ],
          compact: true,
        },
      ],
    },
  ],
  vocabulary: [
    {
      id: 'verb-fut',
      hungarian: 'fut',
      english: 'runs',
      note: 'Group 1 short consonant-ending verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-1',
    },
    {
      id: 'verb-all',
      hungarian: 'áll',
      english: 'stands',
      note: 'Group 1 short consonant-ending verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-1',
    },
    {
      id: 'verb-ul',
      hungarian: 'ül',
      english: 'sits',
      note: 'Group 1 short consonant-ending verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-1',
    },
    {
      id: 'verb-olvas',
      hungarian: 'olvas',
      english: 'reads',
      note: 'Group 2 s-stem verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-2',
    },
    {
      id: 'verb-foz',
      hungarian: 'főz',
      english: 'cooks',
      note: 'Group 2 s-stem verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-2',
    },
    {
      id: 'verb-nez',
      hungarian: 'néz',
      english: 'watches / looks',
      note: 'Group 2 s-stem verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-2',
    },
    {
      id: 'verb-eszik',
      hungarian: 'eszik',
      english: 'eats',
      note: 'Group 3 special -ik verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-3',
    },
    {
      id: 'verb-iszik',
      hungarian: 'iszik',
      english: 'drinks',
      note: 'Group 3 special -ik verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-3',
    },
    {
      id: 'verb-lakik',
      hungarian: 'lakik',
      english: 'lives',
      note: 'Group 4 regular -ik verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-4',
    },
    {
      id: 'verb-jatszik',
      hungarian: 'játszik',
      english: 'plays',
      note: 'Group 4 regular -ik verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-4',
    },
    {
      id: 'verb-furdik',
      hungarian: 'fürdik',
      english: 'bathes / takes a bath',
      note: 'Group 4 regular -ik verb with common learner variants',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-4',
    },
    {
      id: 'verb-alszik',
      hungarian: 'alszik',
      english: 'sleeps',
      note: 'Group 4 regular -ik verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-4',
    },
    {
      id: 'verb-takarit',
      hungarian: 'takarít',
      english: 'cleans / tidies',
      note: 'Group 5 -ít verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-5',
    },
    {
      id: 'verb-fest',
      hungarian: 'fest',
      english: 'paints',
      note: 'Group 5 dense stem verb',
      partOfSpeech: 'verb',
      distractorGroup: 'present-group-5',
    },
    {
      id: 'verb-van',
      hungarian: 'van',
      english: 'is / there is',
      note: 'Irregular anchor',
      partOfSpeech: 'verb',
      distractorGroup: 'present-irregular',
    },
    {
      id: 'verb-megy',
      hungarian: 'megy',
      english: 'goes',
      note: 'Irregular anchor',
      partOfSpeech: 'verb',
      distractorGroup: 'present-irregular',
    },
    {
      id: 'verb-jon',
      hungarian: 'jön',
      english: 'comes',
      note: 'Irregular anchor',
      partOfSpeech: 'verb',
      distractorGroup: 'present-irregular',
    },
  ],
  examples: [
    {
      id: 'present-example-01',
      hungarian: 'Reggel gyorsan futok.',
      english: 'I run quickly in the morning.',
      focus: 'Group 1 regular pattern',
      chunks: ['Reggel', 'gyorsan', 'futok.'],
      targets: [
        {
          text: 'futok',
          kind: 'pattern',
          sourceVocabularyId: 'verb-fut',
          acceptedAnswers: ['futok'],
          distractorGroup: 'present-group-1',
        },
      ],
    },
    {
      id: 'present-example-02',
      hungarian: 'Te most az ajtóban állsz.',
      english: 'You are standing at the door now.',
      focus: 'Group 1 second person',
      chunks: ['Te most', 'az ajtóban', 'állsz.'],
      targets: [
        {
          text: 'állsz',
          kind: 'pattern',
          sourceVocabularyId: 'verb-all',
          acceptedAnswers: ['állsz'],
          distractorGroup: 'present-group-1',
        },
      ],
    },
    {
      id: 'present-example-03',
      hungarian: 'Mi este a parkban ülünk.',
      english: 'We sit in the park in the evening.',
      focus: 'Group 1 first-person plural',
      chunks: ['Mi este', 'a parkban', 'ülünk.'],
      targets: [
        {
          text: 'ülünk',
          kind: 'pattern',
          sourceVocabularyId: 'verb-ul',
          acceptedAnswers: ['ülünk'],
          distractorGroup: 'present-group-1',
        },
      ],
    },
    {
      id: 'present-example-04',
      hungarian: 'Este olvasol vagy főzöl?',
      english: 'Do you read or cook in the evening?',
      focus: 'Group 2 te-form contrast',
      chunks: ['Este', 'olvasol', 'vagy főzöl?'],
      targets: [
        {
          text: 'olvasol',
          kind: 'pattern',
          sourceVocabularyId: 'verb-olvas',
          acceptedAnswers: ['olvasol'],
          distractorGroup: 'present-group-2',
        },
      ],
    },
    {
      id: 'present-example-05',
      hungarian: 'Ti most egy filmet néztek.',
      english: 'You all are watching a film now.',
      focus: 'Group 2 ti-form',
      chunks: ['Ti most', 'egy filmet', 'néztek.'],
      targets: [
        {
          text: 'néztek',
          kind: 'pattern',
          sourceVocabularyId: 'verb-nez',
          acceptedAnswers: ['néztek'],
          distractorGroup: 'present-group-2',
        },
      ],
    },
    {
      id: 'present-example-06',
      hungarian: 'Most eszem.',
      english: 'I am eating now.',
      focus: 'Group 3 first-person singular',
      chunks: ['Most', 'eszem.'],
      targets: [
        {
          text: 'eszem',
          kind: 'pattern',
          sourceVocabularyId: 'verb-eszik',
          acceptedAnswers: ['eszem'],
          distractorGroup: 'present-group-3',
        },
      ],
    },
    {
      id: 'present-example-07',
      hungarian: 'Te most vizet iszol.',
      english: 'You are drinking water now.',
      focus: 'Group 3 second-person singular',
      chunks: ['Te most', 'vizet', 'iszol.'],
      targets: [
        {
          text: 'iszol',
          kind: 'pattern',
          sourceVocabularyId: 'verb-iszik',
          acceptedAnswers: ['iszol'],
          distractorGroup: 'present-group-3',
        },
      ],
    },
    {
      id: 'present-example-08',
      hungarian: 'A család Budapesten lakik.',
      english: 'The family lives in Budapest.',
      focus: 'Group 4 third-person singular',
      chunks: ['A család', 'Budapesten', 'lakik.'],
      targets: [
        {
          text: 'lakik',
          kind: 'pattern',
          sourceVocabularyId: 'verb-lakik',
          acceptedAnswers: ['lakik'],
          distractorGroup: 'present-group-4',
        },
      ],
    },
    {
      id: 'present-example-09',
      hungarian: 'Délután a gyerekek a parkban játszanak.',
      english: 'In the afternoon the children play in the park.',
      focus: 'Group 4 third-person plural',
      chunks: ['Délután', 'a gyerekek a parkban', 'játszanak.'],
      targets: [
        {
          text: 'játszanak',
          kind: 'pattern',
          sourceVocabularyId: 'verb-jatszik',
          acceptedAnswers: ['játszanak'],
          distractorGroup: 'present-group-4',
        },
      ],
    },
    {
      id: 'present-example-10',
      hungarian: 'Reggel gyorsan fürdöm.',
      english: 'I take a bath quickly in the morning.',
      focus: 'Group 4 variant-sensitive first person',
      chunks: ['Reggel', 'gyorsan', 'fürdöm.'],
      targets: [
        {
          text: 'fürdöm',
          kind: 'pattern',
          sourceVocabularyId: 'verb-furdik',
          acceptedAnswers: ['fürdöm', 'fürdök'],
          distractorGroup: 'present-group-4',
        },
      ],
    },
    {
      id: 'present-example-11',
      hungarian: 'A gyerek már alszik.',
      english: 'The child is already sleeping.',
      focus: 'Group 4 stable third person',
      chunks: ['A gyerek', 'már', 'alszik.'],
      targets: [
        {
          text: 'alszik',
          kind: 'pattern',
          sourceVocabularyId: 'verb-alszik',
          acceptedAnswers: ['alszik'],
          distractorGroup: 'present-group-4',
        },
      ],
    },
    {
      id: 'present-example-12',
      hungarian: 'Mi este takarítunk.',
      english: 'We clean in the evening.',
      focus: 'Group 5 first-person plural',
      chunks: ['Mi este', 'takarítunk.'],
      targets: [
        {
          text: 'takarítunk',
          kind: 'pattern',
          sourceVocabularyId: 'verb-takarit',
          acceptedAnswers: ['takarítunk'],
          distractorGroup: 'present-group-5',
        },
      ],
    },
    {
      id: 'present-example-13',
      hungarian: 'A fiúk a garázsban festenek.',
      english: 'The boys paint in the garage.',
      focus: 'Group 5 third-person plural',
      chunks: ['A fiúk', 'a garázsban', 'festenek.'],
      targets: [
        {
          text: 'festenek',
          kind: 'pattern',
          sourceVocabularyId: 'verb-fest',
          acceptedAnswers: ['festenek'],
          distractorGroup: 'present-group-5',
        },
      ],
    },
    {
      id: 'present-example-14',
      hungarian: 'Már a kávézóban vagyunk.',
      english: 'We are already in the café.',
      focus: 'Irregular anchor: van',
      chunks: ['Már', 'a kávézóban', 'vagyunk.'],
      targets: [
        {
          text: 'vagyunk',
          kind: 'pattern',
          sourceVocabularyId: 'verb-van',
          acceptedAnswers: ['vagyunk'],
          distractorGroup: 'present-irregular',
        },
      ],
    },
    {
      id: 'present-example-15',
      hungarian: 'Holnap együtt megyünk a piacra.',
      english: 'Tomorrow we are going together to the market.',
      focus: 'Irregular anchor: megy',
      chunks: ['Holnap', 'együtt', 'megyünk a piacra.'],
      targets: [
        {
          text: 'megyünk',
          kind: 'pattern',
          sourceVocabularyId: 'verb-megy',
          acceptedAnswers: ['megyünk'],
          distractorGroup: 'present-irregular',
        },
      ],
    },
    {
      id: 'present-example-16',
      hungarian: 'Ma korán jövök haza.',
      english: 'I am coming home early today.',
      focus: 'Irregular anchor: jön',
      chunks: ['Ma', 'korán', 'jövök haza.'],
      targets: [
        {
          text: 'jövök',
          kind: 'pattern',
          sourceVocabularyId: 'verb-jon',
          acceptedAnswers: ['jövök'],
          distractorGroup: 'present-irregular',
        },
      ],
    },
  ],
  patterns: [
    {
      id: 'group-1-fut-en',
      prompt: 'Choose the correct én form of fut.',
      englishCue: 'I run quickly in the morning.',
      template: 'Reggel gyorsan ___ .',
      answer: 'futok',
      acceptedAnswers: ['futok'],
      distractors: ['futsz', 'fut', 'futnak'],
      tags: ['group-1', 'én'],
    },
    {
      id: 'group-1-all-te',
      prompt: 'Choose the correct te form of áll.',
      englishCue: 'You are standing at the door now.',
      template: 'Most az ajtóban ___ .',
      answer: 'állsz',
      acceptedAnswers: ['állsz'],
      distractors: ['állok', 'áll', 'állnak'],
      tags: ['group-1', 'te'],
    },
    {
      id: 'group-1-ul-mi',
      prompt: 'Choose the correct mi form of ül.',
      englishCue: 'We sit in the park in the evening.',
      template: 'Mi este a parkban ___ .',
      answer: 'ülünk',
      acceptedAnswers: ['ülünk'],
      distractors: ['ültök', 'ülnek', 'ülsz'],
      tags: ['group-1', 'mi'],
    },
    {
      id: 'group-2-olvas-te',
      prompt: 'Choose the correct te form of olvas.',
      englishCue: 'You read a lot in the evening.',
      template: 'Este sokat ___ .',
      answer: 'olvasol',
      acceptedAnswers: ['olvasol'],
      distractors: ['olvasok', 'olvas', 'olvasnak'],
      tags: ['group-2', 'te'],
    },
    {
      id: 'group-2-foz-te',
      prompt: 'Choose the correct te form of főz.',
      englishCue: 'You cook slowly in the evening.',
      template: 'Este lassan ___ .',
      answer: 'főzöl',
      acceptedAnswers: ['főzöl'],
      distractors: ['főzök', 'főz', 'főznek'],
      tags: ['group-2', 'te'],
    },
    {
      id: 'group-2-nez-ti',
      prompt: 'Choose the correct ti form of néz.',
      englishCue: 'You all are watching a film now.',
      template: 'Ti most egy filmet ___ .',
      answer: 'néztek',
      acceptedAnswers: ['néztek'],
      distractors: ['nézek', 'nézel', 'néznek'],
      tags: ['group-2', 'ti'],
    },
    {
      id: 'group-3-eszik-en',
      prompt: 'Choose the correct én form of eszik.',
      englishCue: 'I am eating a sandwich now.',
      template: 'Most egy szendvicset ___ .',
      answer: 'eszem',
      acceptedAnswers: ['eszem'],
      distractors: ['eszel', 'eszik', 'esznek'],
      tags: ['group-3', 'én'],
    },
    {
      id: 'group-3-iszik-te',
      prompt: 'Choose the correct te form of iszik.',
      englishCue: 'You are drinking water now.',
      template: 'Most vizet ___ .',
      answer: 'iszol',
      acceptedAnswers: ['iszol'],
      distractors: ['iszom', 'iszik', 'isznak'],
      tags: ['group-3', 'te'],
    },
    {
      id: 'group-3-eszik-ok',
      prompt: 'Choose the correct ők form of eszik.',
      englishCue: 'The children eat late.',
      template: 'A gyerekek későn ___ .',
      answer: 'esznek',
      acceptedAnswers: ['esznek'],
      distractors: ['eszem', 'eszel', 'eszik'],
      tags: ['group-3', 'ők'],
    },
    {
      id: 'group-4-lakik-en',
      prompt: 'Choose an accepted én form of lakik.',
      englishCue: 'I live in Budapest.',
      template: 'Budapesten ___ .',
      answer: 'lakom',
      acceptedAnswers: ['lakom', 'lakok'],
      distractors: ['laksz', 'lakik', 'laknak'],
      tags: ['group-4', 'én'],
    },
    {
      id: 'group-4-jatszik-ok',
      prompt: 'Choose the correct ők form of játszik.',
      englishCue: 'They play in the park in the afternoon.',
      template: 'Délután a parkban ___ .',
      answer: 'játszanak',
      acceptedAnswers: ['játszanak'],
      distractors: ['játszom', 'játszol', 'játszik'],
      tags: ['group-4', 'ők'],
    },
    {
      id: 'group-4-furdik-en',
      prompt: 'Choose an accepted én form of fürdik.',
      englishCue: 'I take a bath quickly in the morning.',
      template: 'Reggel gyorsan ___ .',
      answer: 'fürdöm',
      acceptedAnswers: ['fürdöm', 'fürdök'],
      distractors: ['fürdesz', 'fürdik', 'fürdenek'],
      tags: ['group-4', 'én'],
    },
    {
      id: 'group-4-alszik-o',
      prompt: 'Choose the correct ő form of alszik.',
      englishCue: 'The child is already sleeping.',
      template: 'A gyerek már ___ .',
      answer: 'alszik',
      acceptedAnswers: ['alszik'],
      distractors: ['alszom', 'alszol', 'alszanak'],
      tags: ['group-4', 'ő'],
    },
    {
      id: 'group-5-takarit-te',
      prompt: 'Choose the correct te form of takarít.',
      englishCue: 'You clean thoroughly at home.',
      template: 'Otthon alaposan ___ .',
      answer: 'takarítasz',
      acceptedAnswers: ['takarítasz'],
      distractors: ['takarítok', 'takarít', 'takarítanak'],
      tags: ['group-5', 'te'],
    },
    {
      id: 'group-5-fest-te',
      prompt: 'Choose the correct te form of fest.',
      englishCue: 'You paint very nicely.',
      template: 'Nagyon szépen ___ .',
      answer: 'festesz',
      acceptedAnswers: ['festesz'],
      distractors: ['festek', 'fest', 'festenek'],
      tags: ['group-5', 'te'],
    },
    {
      id: 'group-5-fest-ok',
      prompt: 'Choose the correct ők form of fest.',
      englishCue: 'The boys paint in the garage.',
      template: 'A fiúk a garázsban ___ .',
      answer: 'festenek',
      acceptedAnswers: ['festenek'],
      distractors: ['festek', 'festesz', 'fest'],
      tags: ['group-5', 'ők'],
    },
    {
      id: 'irregular-van-mi',
      prompt: 'Choose the correct mi form of van.',
      englishCue: 'We are already in the café.',
      template: 'Már a kávézóban ___ .',
      answer: 'vagyunk',
      acceptedAnswers: ['vagyunk'],
      distractors: ['vagyok', 'vagytok', 'vannak'],
      tags: ['irregular', 'mi'],
    },
    {
      id: 'irregular-megy-te',
      prompt: 'Choose the correct te form of megy.',
      englishCue: 'You are going to the market early tomorrow.',
      template: 'Holnap korán piacra ___ .',
      answer: 'mész',
      acceptedAnswers: ['mész'],
      distractors: ['megyek', 'megy', 'mennek'],
      tags: ['irregular', 'te'],
    },
    {
      id: 'irregular-megy-ok',
      prompt: 'Choose the correct ők form of megy.',
      englishCue: 'They go by bus every morning.',
      template: 'Minden reggel busszal ___ .',
      answer: 'mennek',
      acceptedAnswers: ['mennek'],
      distractors: ['megyek', 'mész', 'megy'],
      tags: ['irregular', 'ők'],
    },
    {
      id: 'irregular-jon-en',
      prompt: 'Choose the correct én form of jön.',
      englishCue: 'I am coming home early today.',
      template: 'Ma korán haza ___ .',
      answer: 'jövök',
      acceptedAnswers: ['jövök'],
      distractors: ['jössz', 'jön', 'jönnek'],
      tags: ['irregular', 'én'],
    },
    {
      id: 'irregular-jon-ti',
      prompt: 'Choose the correct ti form of jön.',
      englishCue: 'When are you all coming home?',
      template: 'Ti mikor ___ haza?',
      answer: 'jöttök',
      acceptedAnswers: ['jöttök'],
      distractors: ['jövök', 'jössz', 'jönnek'],
      tags: ['irregular', 'ti'],
    },
  ],
  practice: {
    generators: [
      { key: 'pattern_choice', category: 'core' },
      { key: 'pattern_transform', category: 'core' },
      { key: 'example_cloze', category: 'core' },
      { key: 'example_ordering', category: 'review' },
      { key: 'vocabulary_reverse_choice', category: 'review' },
      { key: 'vocabulary_flashcards', category: 'review' },
      { key: 'review_weak_mix', category: 'review' },
    ],
    sessionDefaults: {
      roundSize: 8,
      reviewSize: 8,
    },
    disableDuplicateGeneratedActivities: true,
  },
  practiceSets: [],
}
