import type { ExampleItem, Lesson, VocabularyItem } from './types'

const coreVocabularyEntries = [
  // 1-100
  ['a', 'the'],
  ['az', 'the / that'],
  ['egy', 'one / a'],
  ['és', 'and'],
  ['vagy', 'or / are'],
  ['de', 'but'],
  ['hogy', 'that / how'],
  ['nem', 'not'],
  ['igen', 'yes'],
  ['van', 'is / there is'],
  ['nincs', 'is not / there is no'],
  ['is', 'also'],
  ['én', 'I'],
  ['te', 'you'],
  ['ő', 'he / she'],
  ['mi', 'we'],
  ['ti', 'you (plural)'],
  ['ők', 'they'],
  ['ez', 'this'],
  ['itt', 'here'],
  ['ott', 'there'],
  ['hol', 'where'],
  ['mikor', 'when'],
  ['miért', 'why'],
  ['hogyan', 'how'],
  ['melyik', 'which'],
  ['mennyi', 'how much'],
  ['sok', 'many / much'],
  ['kevés', 'little / few'],
  ['minden', 'every / all'],
  ['semmi', 'nothing'],
  ['valami', 'something'],
  ['valaki', 'someone'],
  ['már', 'already'],
  ['még', 'still / yet'],
  ['mindig', 'always'],
  ['gyakran', 'often'],
  ['néha', 'sometimes'],
  ['soha', 'never'],
  ['most', 'now'],
  ['ma', 'today'],
  ['tegnap', 'yesterday'],
  ['holnap', 'tomorrow'],
  ['reggel', 'morning'],
  ['este', 'evening'],
  ['éjjel', 'at night'],
  ['nap', 'day / sun'],
  ['hét', 'week'],
  ['hónap', 'month'],
  ['év', 'year'],
  ['idő', 'time / weather'],
  ['óra', 'hour / clock'],
  ['perc', 'minute'],
  ['ember', 'person'],
  ['nő', 'woman'],
  ['férfi', 'man'],
  ['gyerek', 'child'],
  ['család', 'family'],
  ['barát', 'friend'],
  ['név', 'name'],
  ['nyelv', 'language'],
  ['ország', 'country'],
  ['város', 'city'],
  ['ház', 'house'],
  ['út', 'road / way'],
  ['hely', 'place'],
  ['munka', 'work'],
  ['iskola', 'school'],
  ['pénz', 'money'],
  ['étel', 'food'],
  ['víz', 'water'],
  ['kenyér', 'bread'],
  ['kávé', 'coffee'],
  ['tea', 'tea'],
  ['autó', 'car'],
  ['busz', 'bus'],
  ['vonat', 'train'],
  ['bolt', 'shop'],
  ['orvos', 'doctor'],
  ['szó', 'word'],
  ['könyv', 'book'],
  ['dolog', 'thing'],
  ['jó', 'good'],
  ['rossz', 'bad'],
  ['nagy', 'big'],
  ['kicsi', 'small'],
  ['új', 'new'],
  ['régi', 'old'],
  ['szép', 'beautiful / nice'],
  ['fontos', 'important'],
  ['könnyű', 'easy / light'],
  ['nehéz', 'difficult / heavy'],
  ['gyors', 'fast'],
  ['lassú', 'slow'],
  ['meleg', 'warm'],
  ['hideg', 'cold'],
  ['nyitva', 'open'],
  ['zárva', 'closed'],
  ['szia', 'hi / bye'],
  ['köszönöm', 'thank you'],
  // 101-200
  ['kérem', 'please / I ask'],
  ['viszlát', 'goodbye'],
  ['bocsánat', 'sorry / excuse me'],
  ['otthon', 'at home'],
  ['szoba', 'room'],
  ['ajtó', 'door'],
  ['ablak', 'window'],
  ['asztal', 'table'],
  ['szék', 'chair'],
  ['ágy', 'bed'],
  ['konyha', 'kitchen'],
  ['fürdőszoba', 'bathroom'],
  ['kert', 'garden'],
  ['utca', 'street'],
  ['tér', 'square'],
  ['állomás', 'station'],
  ['repülőtér', 'airport'],
  ['piac', 'market'],
  ['étterem', 'restaurant'],
  ['kávézó', 'cafe'],
  ['szálloda', 'hotel'],
  ['iroda', 'office'],
  ['tanár', 'teacher'],
  ['diák', 'student'],
  ['kolléga', 'colleague'],
  ['szomszéd', 'neighbor'],
  ['anya', 'mother'],
  ['apa', 'father'],
  ['fiú', 'boy / son'],
  ['lány', 'girl / daughter'],
  ['testvér', 'sibling'],
  ['férj', 'husband'],
  ['feleség', 'wife'],
  ['reggeli', 'breakfast'],
  ['ebéd', 'lunch'],
  ['vacsora', 'dinner'],
  ['alma', 'apple'],
  ['banán', 'banana'],
  ['hús', 'meat'],
  ['hal', 'fish'],
  ['csirke', 'chicken'],
  ['leves', 'soup'],
  ['sajt', 'cheese'],
  ['tej', 'milk'],
  ['cukor', 'sugar'],
  ['só', 'salt'],
  ['bors', 'pepper'],
  ['sör', 'beer'],
  ['bor', 'wine'],
  ['gyümölcs', 'fruit'],
  ['zöldség', 'vegetable'],
  ['tojás', 'egg'],
  ['krumpli', 'potato'],
  ['rizs', 'rice'],
  ['pékség', 'bakery'],
  ['bevásárlás', 'shopping'],
  ['ár', 'price'],
  ['forint', 'forint'],
  ['számla', 'bill'],
  ['jegy', 'ticket'],
  ['útlevél', 'passport'],
  ['táska', 'bag'],
  ['cipő', 'shoe'],
  ['kabát', 'coat'],
  ['ruha', 'dress / clothing'],
  ['nadrág', 'trousers'],
  ['póló', 'T-shirt'],
  ['telefon', 'phone'],
  ['számítógép', 'computer'],
  ['internet', 'internet'],
  ['levél', 'letter'],
  ['üzenet', 'message'],
  ['zene', 'music'],
  ['film', 'film'],
  ['kép', 'picture'],
  ['hír', 'news'],
  ['játék', 'game'],
  ['sport', 'sport'],
  ['futball', 'football'],
  ['úszás', 'swimming'],
  ['futás', 'running'],
  ['séta', 'walk'],
  ['vásárol', 'shop / buy'],
  ['fizet', 'pay'],
  ['ad', 'give'],
  ['kap', 'receive / get'],
  ['kér', 'ask for'],
  ['mond', 'say'],
  ['beszél', 'speak'],
  ['hall', 'hear'],
  ['lát', 'see'],
  ['néz', 'look / watch'],
  ['olvas', 'read'],
  ['ír', 'write'],
  ['tanul', 'study / learn'],
  ['tanít', 'teach'],
  ['dolgozik', 'work'],
  ['lakik', 'live (reside)'],
  ['eszik', 'eat'],
  ['iszik', 'drink'],
  // 201-300
  ['megy', 'go'],
  ['jön', 'come'],
  ['marad', 'stay'],
  ['indul', 'leave / depart'],
  ['érkezik', 'arrive'],
  ['vesz', 'buy / take'],
  ['talál', 'find'],
  ['keres', 'look for'],
  ['használ', 'use'],
  ['szeret', 'love / like'],
  ['tud', 'know / can'],
  ['akar', 'want'],
  ['kell', 'need / must'],
  ['lehet', 'can / may / possible'],
  ['él', 'live'],
  ['alszik', 'sleep'],
  ['kel', 'get up / rise'],
  ['ül', 'sit'],
  ['áll', 'stand'],
  ['fekszik', 'lie down'],
  ['nyit', 'open'],
  ['zár', 'close'],
  ['hoz', 'bring'],
  ['visz', 'take / carry'],
  ['vár', 'wait'],
  ['segít', 'help'],
  ['kezd', 'begin'],
  ['befejez', 'finish'],
  ['kérdez', 'ask'],
  ['felel', 'answer / reply'],
  ['dolgozó', 'worker'],
  ['ügyfél', 'customer'],
  ['rendőr', 'police officer'],
  ['posta', 'post office'],
  ['bank', 'bank'],
  ['kórház', 'hospital'],
  ['gyógyszertár', 'pharmacy'],
  ['park', 'park'],
  ['híd', 'bridge'],
  ['folyó', 'river'],
  ['tó', 'lake'],
  ['hegy', 'mountain'],
  ['tenger', 'sea'],
  ['időjárás', 'weather'],
  ['eső', 'rain'],
  ['hó', 'snow'],
  ['szél', 'wind'],
  ['napfény', 'sunshine'],
  ['felhő', 'cloud'],
  ['tavasz', 'spring'],
  ['nyár', 'summer'],
  ['ősz', 'autumn'],
  ['tél', 'winter'],
  ['hétfő', 'Monday'],
  ['kedd', 'Tuesday'],
  ['szerda', 'Wednesday'],
  ['csütörtök', 'Thursday'],
  ['péntek', 'Friday'],
  ['szombat', 'Saturday'],
  ['vasárnap', 'Sunday'],
  ['január', 'January'],
  ['február', 'February'],
  ['március', 'March'],
  ['április', 'April'],
  ['május', 'May'],
  ['június', 'June'],
  ['július', 'July'],
  ['augusztus', 'August'],
  ['szeptember', 'September'],
  ['október', 'October'],
  ['november', 'November'],
  ['december', 'December'],
  ['egyedül', 'alone'],
  ['együtt', 'together'],
  ['bent', 'inside'],
  ['kint', 'outside'],
  ['előtt', 'before / in front of'],
  ['után', 'after'],
  ['alatt', 'under'],
  ['fölött', 'above'],
  ['mellett', 'beside'],
  ['között', 'between'],
  ['nélkül', 'without'],
  ['miatt', 'because of'],
  ['szerint', 'according to'],
  ['felé', 'toward'],
  ['innen', 'from here'],
  ['onnan', 'from there'],
  ['oda', 'to there'],
  ['vissza', 'back'],
  ['bal', 'left'],
  ['jobb', 'right'],
  ['egyenes', 'straight'],
  ['közel', 'near'],
  ['messze', 'far'],
  ['első', 'first'],
  ['utolsó', 'last'],
  ['második', 'second'],
  ['harmadik', 'third'],
  ['központ', 'center'],
  // 301-400
  ['környék', 'neighborhood'],
  ['utazás', 'travel'],
  ['látogatás', 'visit'],
  ['találkozó', 'meeting'],
  ['program', 'plan / program'],
  ['munkahely', 'workplace'],
  ['egyetem', 'university'],
  ['tanfolyam', 'course'],
  ['feladat', 'task'],
  ['példa', 'example'],
  ['lehetőség', 'opportunity'],
  ['segítség', 'help'],
  ['probléma', 'problem'],
  ['megoldás', 'solution'],
  ['igaz', 'true / right'],
  ['hamis', 'false'],
  ['biztos', 'sure / certain'],
  ['talán', 'maybe'],
  ['persze', 'of course'],
  ['rendben', 'all right / okay'],
  ['örül', 'be glad'],
  ['fél', 'be afraid'],
  ['remél', 'hope'],
  ['hisz', 'believe'],
  ['gondol', 'think'],
  ['emlékszik', 'remember'],
  ['felejt', 'forget'],
  ['ért', 'understand'],
  ['tanács', 'advice'],
  ['ötlet', 'idea'],
  ['cél', 'goal'],
  ['terv', 'plan'],
  ['döntés', 'decision'],
  ['változás', 'change'],
  ['kezdet', 'beginning'],
  ['vég', 'end'],
  ['siker', 'success'],
  ['hiba', 'mistake'],
  ['igazság', 'truth'],
  ['béke', 'peace'],
  ['világ', 'world'],
  ['élet', 'life'],
  ['halál', 'death'],
  ['test', 'body'],
  ['fej', 'head'],
  ['szem', 'eye'],
  ['kéz', 'hand'],
  ['láb', 'leg / foot'],
  ['szív', 'heart'],
  ['gyomor', 'stomach'],
  ['betegség', 'illness'],
  ['egészség', 'health'],
  ['fájdalom', 'pain'],
  ['gyógyszer', 'medicine'],
  ['erős', 'strong'],
  ['gyenge', 'weak'],
  ['boldog', 'happy'],
  ['szomorú', 'sad'],
  ['dühös', 'angry'],
  ['fáradt', 'tired'],
  ['beteg', 'sick'],
  ['egészséges', 'healthy'],
  ['éhes', 'hungry'],
  ['szomjas', 'thirsty'],
  ['kész', 'ready'],
  ['tiszta', 'clean'],
  ['piszkos', 'dirty'],
  ['drága', 'expensive / dear'],
  ['olcsó', 'cheap'],
  ['tele', 'full'],
  ['üres', 'empty'],
  ['csendes', 'quiet'],
  ['hangos', 'loud'],
  ['világos', 'bright / clear'],
  ['sötét', 'dark'],
  ['egyszerű', 'simple'],
  ['bonyolult', 'complicated'],
  ['érdekes', 'interesting'],
  ['unalmas', 'boring'],
  ['kedves', 'kind / nice'],
  ['barátságos', 'friendly'],
  ['udvarias', 'polite'],
  ['pontos', 'punctual / exact'],
  ['korai', 'early'],
  ['késő', 'late'],
  ['hamar', 'soon'],
  ['lassan', 'slowly'],
  ['gyorsan', 'quickly'],
  ['jól', 'well'],
  ['rosszul', 'badly'],
  ['sokáig', 'for a long time'],
  ['azonnal', 'immediately'],
  ['általában', 'usually'],
  ['különösen', 'especially'],
  ['néhány', 'some'],
  ['több', 'more'],
  ['kevesebb', 'less / fewer'],
  ['más', 'other'],
  ['ugyanaz', 'same'],
  ['különböző', 'different'],
  // 401-500
  ['mindenki', 'everyone'],
  ['senki', 'no one'],
  ['valahol', 'somewhere'],
  ['bárhol', 'anywhere'],
  ['sehol', 'nowhere'],
  ['egyszer', 'once'],
  ['kétszer', 'twice'],
  ['gyakorlás', 'practice'],
  ['ismétlés', 'repetition / review'],
  ['kártya', 'card'],
  ['memória', 'memory'],
  ['szókincs', 'vocabulary'],
  ['jelentés', 'meaning'],
  ['fordítás', 'translation'],
  ['kiejtés', 'pronunciation'],
  ['hang', 'sound / voice'],
  ['kérés', 'request'],
  ['rendelés', 'order'],
  ['szolgáltatás', 'service'],
  ['ügy', 'matter / case'],
  ['hivatal', 'office / authority'],
  ['papír', 'paper'],
  ['toll', 'pen'],
  ['ceruza', 'pencil'],
  ['füzet', 'notebook'],
  ['tábla', 'board'],
  ['kulcs', 'key'],
  ['pénztárca', 'wallet'],
  ['szemüveg', 'glasses'],
  ['lámpa', 'lamp'],
  ['vonal', 'line'],
  ['sarok', 'corner'],
  ['emelet', 'floor / story'],
  ['lift', 'elevator'],
  ['lépcső', 'stairs'],
  ['bejárat', 'entrance'],
  ['kijárat', 'exit'],
  ['térkép', 'map'],
  ['cím', 'address'],
  ['szám', 'number'],
  ['dátum', 'date'],
  ['időpont', 'appointment'],
  ['bérlet', 'pass / season ticket'],
  ['csomag', 'package'],
  ['csap', 'tap / faucet'],
  ['törölköző', 'towel'],
  ['takaró', 'blanket'],
  ['mosás', 'washing'],
  ['főzés', 'cooking'],
  ['takarítás', 'cleaning'],
  ['javítás', 'repair'],
  ['munkaidő', 'working hours'],
  ['szünet', 'break'],
  ['ünnep', 'holiday'],
  ['hétvége', 'weekend'],
  ['regisztráció', 'registration'],
  ['jelszó', 'password'],
  ['alkalmazás', 'app / application'],
  ['weboldal', 'website'],
  ['e-mail', 'email'],
  ['hívás', 'call'],
  ['találat', 'result / hit'],
  ['választás', 'choice / election'],
  ['szokás', 'habit / custom'],
  ['történet', 'story'],
  ['beszélgetés', 'conversation'],
  ['válaszol', 'answer'],
  ['mutat', 'show'],
  ['tanácsol', 'advise'],
  ['nyer', 'win'],
  ['veszít', 'lose'],
  ['próbál', 'try'],
  ['sikerül', 'succeed'],
  ['javul', 'improve'],
  ['fejlődik', 'develop / improve'],
  ['ismétel', 'repeat'],
  ['gyakorol', 'practice'],
  ['folytat', 'continue'],
  ['kezdő', 'beginner'],
  ['haladó', 'advanced'],
  ['teljes', 'complete'],
  ['szabad', 'free / allowed'],
  ['elfoglalt', 'busy'],
  ['szükséges', 'necessary'],
  ['közös', 'shared / common'],
  ['saját', 'own'],
  ['legjobb', 'best'],
  ['legrosszabb', 'worst'],
  ['sokan', 'many people'],
  ['kevésbé', 'less'],
  ['általános', 'general'],
  ['mindennapi', 'everyday'],
  ['kapcsolat', 'relationship / contact'],
  ['rendszer', 'system'],
  ['adat', 'data'],
  ['jegyzet', 'note'],
  ['jövő', 'future'],
  ['múlt', 'past'],
  ['jelen', 'present'],
  ['tapasztalat', 'experience'],
] as const

const coreVocabulary: VocabularyItem[] = coreVocabularyEntries.map(
  ([hungarian, english]) => ({
    hungarian,
    english,
  }),
)

interface VocabularyBand {
  id: string
  level: string
  title: string
  subtitle: string
  summary: string
  sourceUnit: string
  start: number
  end: number
  examples: ExampleItem[]
}

const sharedGoals = [
  'Recognize and recall a focused 100-word block quickly.',
  'Use repeatable flashcard rounds instead of one long memorization session.',
  'Turn isolated words into reusable short phrases through repeated exposure.',
]

const sharedStudyFlow = [
  'Scan the list once before practice so the first flashcard round is not completely cold.',
  'Run a 20-card round and say the Hungarian side aloud before you flip the card.',
  'Mark cards honestly with Again or I know this so the score reflects real recall.',
  'Repeat the lesson across multiple short rounds until the weak cards stop slowing you down.',
]

const sharedExplanations = [
  {
    title: 'High-frequency vocabulary compounds fast',
    body:
      'A small, repeated core vocabulary does more real work than a huge unreviewed list. These words reappear in greetings, transport, daily routine, and basic conversation.',
  },
  {
    title: 'Flashcards only help when recall is active',
    body:
      'Do not wait for the back of the card to tell you the answer. Try to say the Hungarian word first, then flip and rate how solid the recall really was.',
  },
  {
    title: 'Short rounds beat one long cram session',
    body:
      'Twenty cards are easy to rerun immediately. Repeated short rounds create better retention than one exhausting pass through an entire hundred-word list.',
  },
]

const vocabularyBands: VocabularyBand[] = [
  {
    id: 'core-vocabulary-001-100',
    level: 'A1',
    title: 'Core Vocabulary 001-100',
    subtitle: 'Start with the words that hold basic everyday Hungarian together.',
    summary:
      'This first 100-word band covers the essential glue words, pronouns, early nouns, and basic descriptions that show up constantly in beginner Hungarian.',
    sourceUnit: 'High-frequency vocabulary 001-100',
    start: 0,
    end: 100,
    examples: [
      { hungarian: 'Hol van a víz?', english: 'Where is the water?', focus: 'Basic question' },
      { hungarian: 'Ez fontos.', english: 'This is important.', focus: 'Simple statement' },
      { hungarian: 'Ma jó nap van.', english: 'Today is a good day.', focus: 'Daily phrase' },
    ],
  },
  {
    id: 'core-vocabulary-101-200',
    level: 'A1',
    title: 'Core Vocabulary 101-200',
    subtitle: 'Add home, family, food, and daily routine language.',
    summary:
      'This 100-word block expands into the vocabulary of home life, shopping, food, family, and the most common study and communication verbs.',
    sourceUnit: 'High-frequency vocabulary 101-200',
    start: 100,
    end: 200,
    examples: [
      { hungarian: 'A család otthon van.', english: 'The family is at home.', focus: 'Home and family' },
      { hungarian: 'Reggeli után tanulok.', english: 'After breakfast I study.', focus: 'Daily routine' },
      { hungarian: 'A diák olvas és ír.', english: 'The student reads and writes.', focus: 'Study actions' },
    ],
  },
  {
    id: 'core-vocabulary-201-300',
    level: 'A1-A2',
    title: 'Core Vocabulary 201-300',
    subtitle: 'Cover movement, places, weather, dates, and directions.',
    summary:
      'This third band adds motion verbs, transport language, weekdays, months, weather, and direction words that support real-world navigation and planning.',
    sourceUnit: 'High-frequency vocabulary 201-300',
    start: 200,
    end: 300,
    examples: [
      { hungarian: 'A vonat most érkezik.', english: 'The train is arriving now.', focus: 'Travel update' },
      { hungarian: 'A park a központ mellett van.', english: 'The park is next to the center.', focus: 'Direction phrase' },
      { hungarian: 'Szombat után vasárnap jön.', english: 'Sunday comes after Saturday.', focus: 'Time sequence' },
    ],
  },
  {
    id: 'core-vocabulary-301-400',
    level: 'A2',
    title: 'Core Vocabulary 301-400',
    subtitle: 'Describe people, feelings, qualities, and common situations.',
    summary:
      'This section strengthens expressive vocabulary: emotions, body words, health, evaluation, and the adverbs and adjectives that make simple speech more precise.',
    sourceUnit: 'High-frequency vocabulary 301-400',
    start: 300,
    end: 400,
    examples: [
      { hungarian: 'Bocsánat, nem értem.', english: 'Sorry, I do not understand.', focus: 'Conversation repair' },
      { hungarian: 'Ez érdekes, de nehéz.', english: 'This is interesting, but difficult.', focus: 'Evaluation' },
      { hungarian: 'Boldog vagyok. Minden rendben.', english: 'I am happy. Everything is all right.', focus: 'Feeling and status' },
    ],
  },
  {
    id: 'core-vocabulary-401-500',
    level: 'A2',
    title: 'Core Vocabulary 401-500',
    subtitle: 'Finish the track with study, service, review, and practical life words.',
    summary:
      'The final 100-word band pushes into repetition, services, admin, technology, and long-term vocabulary-building language so the track supports continued review.',
    sourceUnit: 'High-frequency vocabulary 401-500',
    start: 400,
    end: 500,
    examples: [
      { hungarian: 'A szókincs ismétléssel javul.', english: 'Vocabulary improves with repetition.', focus: 'Review mindset' },
      { hungarian: 'Az alkalmazás segít a gyakorlásban.', english: 'The app helps with practice.', focus: 'Tool language' },
      { hungarian: 'Folytatom a beszélgetést, és gyakorolok.', english: 'I continue the conversation, and I practice.', focus: 'Continuation' },
    ],
  },
]

function buildFlashcardPracticeSet(id: string, items: VocabularyItem[]) {
  return {
    id: `${id}-flashcards`,
    type: 'flashcards' as const,
    title: 'Repeatable flashcard review',
    instructions:
      'Each round shuffles 20 cards from this 100-word lesson. Flip each card only after active recall, then rerun the round as often as needed.',
    cards: items.map((item) => ({
      front: item.hungarian,
      back: item.english,
      note: item.note,
    })),
    sessionSize: 20,
    frontLabel: 'Hungarian',
    backLabel: 'English',
  }
}

function createVocabularyLesson(band: VocabularyBand): Lesson {
  const items = coreVocabulary.slice(band.start, band.end)

  return {
    id: band.id,
    trackId: 'core-vocabulary',
    topics: ['vocabulary', 'frequency', 'flashcards'],
    level: band.level,
    title: band.title,
    subtitle: band.subtitle,
    summary: band.summary,
    sourceUnits: [band.sourceUnit],
    goals: sharedGoals,
    studyFlow: sharedStudyFlow,
    explanations: sharedExplanations,
    vocabulary: items,
    examples: band.examples,
    practiceSets: [buildFlashcardPracticeSet(band.id, items)],
  }
}

export const vocabularyLessons: Lesson[] = vocabularyBands.map(
  createVocabularyLesson,
)
