import { buildScenarioFlashcardCards, createFlashcardPracticeSet } from './practice-helpers'
import type { Lesson } from './types'

export const grammarLessons: Lesson[] = [
  {
    id: 'articles-and-descriptions',
    trackId: 'core-grammar',
    topics: ['articles', 'descriptions'],
    level: 'A1',
    title: 'Articles and Descriptions',
    subtitle: 'Name simple objects and describe them with one clear adjective.',
    summary:
      'This lesson pulls from Unit 2 object and adjective work so you can handle short questions like Mi ez? and Milyen? in more than one scene, not only as isolated grammar prompts.',
    sourceUnits: ['Unit 2'],
    goals: [
      'Use a and az with simple nouns.',
      'Ask and answer Mi ez? in short object-identification scenes.',
      'Describe a noun with a high-frequency adjective.',
      'Notice how the same object can be named first and described second.',
    ],
    studyFlow: [
      'First name the object with Ez egy..., then add one adjective in a second sentence.',
      'Practice vowel-starting and consonant-starting nouns in separate mini-rounds.',
      'Use the same noun with two different adjectives so the pattern feels reusable.',
      'Read the examples aloud as if you were pointing to real objects around you.',
    ],
    explanations: [
      {
        title: 'a and az',
        body:
          'Hungarian switches between a and az depending on the sound that follows. Az is used before vowel sounds, while a is used before consonant sounds.',
      },
      {
        title: 'Mi ez? / Milyen?',
        body:
          'Mi ez? asks what something is. Milyen? asks what it is like. This is a productive pair for beginner speaking because it lets you move from naming to describing.',
      },
      {
        title: 'Adjective placement',
        body:
          'A short adjective like nagy, kicsi, gyors, or lassú can be added directly to a sentence without extra linking words.',
      },
      {
        title: 'Real scenes are better than word lists',
        body:
          'It is easier to remember these patterns when you attach them to an object in front of you: a car outside, an apple on the table, or a mouse in a picture.',
      },
    ],
    vocabulary: [
      { hungarian: 'autó', english: 'car' },
      { hungarian: 'csiga', english: 'snail' },
      { hungarian: 'egér', english: 'mouse' },
      { hungarian: 'alma', english: 'apple' },
      { hungarian: 'nagy', english: 'big' },
      { hungarian: 'kicsi', english: 'small' },
      { hungarian: 'lassú', english: 'slow' },
      { hungarian: 'gyors', english: 'fast' },
    ],
    examples: [
      {
        hungarian: 'Mi ez? Ez egy autó.',
        english: 'What is this? This is a car.',
        focus: 'Naming an object',
      },
      {
        hungarian: 'Az autó gyors.',
        english: 'The car is fast.',
        focus: 'Article + adjective',
      },
      {
        hungarian: 'A csiga lassú.',
        english: 'The snail is slow.',
        focus: 'Simple description',
      },
      {
        hungarian: 'Ez egy alma. Az alma kicsi.',
        english: 'This is an apple. The apple is small.',
        focus: 'Name first, describe second',
      },
      {
        hungarian: 'Az egér kicsi, de gyors.',
        english: 'The mouse is small but fast.',
        focus: 'Two adjectives in contrast',
      },
      {
        hungarian: 'Milyen az autó? Nagy és gyors.',
        english: 'What is the car like? Big and fast.',
        focus: 'Question + answer pair',
      },
    ],
    practiceSets: [
      {
        id: 'articles-fill',
        type: 'fill',
        title: 'Choose the correct article or adjective',
        instructions:
          'Work with the sentence frame and choose the form that sounds right.',
        questions: [
          {
            id: 'a1',
            prompt: 'Use the article before a vowel-starting noun.',
            template: '___ egér kicsi.',
            choices: ['Az', 'A', 'Egy'],
            answer: 'Az',
            note: 'Az is the natural choice before egér.',
          },
          {
            id: 'a2',
            prompt: 'Describe a snail.',
            template: 'A csiga ___.',
            choices: ['lassú', 'drága', 'gyors'],
            answer: 'lassú',
            note: 'This is a clear beginner adjective pattern.',
          },
          {
            id: 'a3',
            prompt: 'Answer "What is this?"',
            template: 'Ez egy ___.',
            choices: ['autó', 'lassú', 'milyen'],
            answer: 'autó',
            note: 'The answer to Mi ez? needs a noun here.',
          },
          {
            id: 'a4',
            prompt: 'Describe the car in one word.',
            template: 'Az autó ___.',
            choices: ['gyors', 'egér', 'ez'],
            answer: 'gyors',
            note: 'Use an adjective, not another noun.',
          },
          {
            id: 'a5',
            prompt: 'Choose the article before alma.',
            template: '___ alma kicsi.',
            choices: ['Az', 'A', 'Mi'],
            answer: 'Az',
            note: 'Alma starts with a vowel sound, so az is the natural form.',
          },
          {
            id: 'a6',
            prompt: 'Give the answer to Milyen az egér?',
            template: 'Az egér ___.',
            choices: ['kicsi', 'autó', 'ez'],
            answer: 'kicsi',
            note: 'Milyen? asks for description, so answer with an adjective.',
          },
        ],
      },
      {
        id: 'articles-match',
        type: 'match',
        title: 'Match object words to meaning',
        instructions: 'Pair the Hungarian item with its English meaning.',
        pairs: [
          { left: 'autó', right: 'car' },
          { left: 'csiga', right: 'snail' },
          { left: 'egér', right: 'mouse' },
          { left: 'alma', right: 'apple' },
          { left: 'nagy', right: 'big' },
          { left: 'kicsi', right: 'small' },
          { left: 'lassú', right: 'slow' },
          { left: 'gyors', right: 'fast' },
        ],
      },
      createFlashcardPracticeSet({
        id: 'articles-scenario-flashcards',
        title: 'Scenario flashcards for naming and describing',
        instructions:
          'Look at the scene prompt, say the Hungarian sentence, then flip the card.',
        cards: buildScenarioFlashcardCards([
          {
            scenario: 'You point to a car and say: This is a car.',
            answer: 'Ez egy autó.',
          },
          {
            scenario: 'You describe the car as fast.',
            answer: 'Az autó gyors.',
          },
          {
            scenario: 'You describe the snail as slow.',
            answer: 'A csiga lassú.',
          },
          {
            scenario: 'You point to an apple and say: The apple is small.',
            answer: 'Az alma kicsi.',
          },
          {
            scenario: 'You ask: What is this?',
            answer: 'Mi ez?',
          },
          {
            scenario: 'You ask: What is the mouse like?',
            answer: 'Milyen az egér?',
          },
        ]),
        sessionSize: 6,
        frontLabel: 'Scene',
        backLabel: 'Hungarian sentence',
      }),
    ],
  },
  {
    id: 'ban-ben-locations',
    trackId: 'core-grammar',
    topics: ['location', 'present'],
    level: 'A1',
    title: 'Location with -ban / -ben',
    subtitle: 'Talk about being in places and doing simple actions there.',
    summary:
      'Unit 5 introduces a key location pattern. This portal reduces it to reusable daily scenes so you can say who is in a place and what they are doing there.',
    sourceUnits: ['Unit 5'],
    goals: [
      'Recognize the idea of "in" with -ban and -ben.',
      'Choose a location form that fits the noun.',
      'Talk about simple actions happening in a place.',
      'Reuse the same action frame in several everyday locations.',
    ],
    studyFlow: [
      'Learn each location as a chunk: a parkban, a boltban, az étteremben.',
      'Attach one action to every place so the form becomes part of a real sentence.',
      'Run the same sentence with different locations, for example tanul, vásárol, ül, olvas.',
      'Use the examples to imagine a classroom, shop, or restaurant instead of memorizing endings in isolation.',
    ],
    explanations: [
      {
        title: '-ban / -ben',
        body:
          'These endings express "in" or "inside". Which form appears depends on vowel harmony, so the right ending has to be learned together with the noun.',
      },
      {
        title: 'Short action sentences',
        body:
          'A1 conversation often depends on small sentences such as A boltban vásárolok or Az étteremben ülünk. They are simple but very useful.',
      },
      {
        title: 'Chunk learning helps',
        body:
          'Instead of memorizing endings in isolation, store whole combinations like a teremben, a házban, a parkban.',
      },
      {
        title: 'Real location scenes repeat constantly',
        body:
          'You will keep saying where you study, shop, sit, wait, or meet someone. That makes location sentences worth overlearning early.',
      },
    ],
    vocabulary: [
      { hungarian: 'teremben', english: 'in the classroom / hall' },
      { hungarian: 'házban', english: 'in the house' },
      { hungarian: 'parkban', english: 'in the park' },
      { hungarian: 'boltban', english: 'in the shop' },
      { hungarian: 'étteremben', english: 'in the restaurant' },
      { hungarian: 'könyvtárban', english: 'in the library' },
      { hungarian: 'iskolában', english: 'in the school' },
      { hungarian: 'kávézóban', english: 'in the café' },
    ],
    examples: [
      {
        hungarian: 'A diák a teremben tanul.',
        english: 'The student is studying in the classroom.',
        focus: 'Location + action',
      },
      {
        hungarian: 'A nő a boltban vásárol.',
        english: 'The woman is shopping in the store.',
        focus: 'Daily action',
      },
      {
        hungarian: 'A fiú a parkban fut.',
        english: 'The boy is running in the park.',
        focus: 'Movement in place',
      },
      {
        hungarian: 'A férfi az étteremben ül.',
        english: 'The man is sitting in the restaurant.',
        focus: 'Still action in a place',
      },
      {
        hungarian: 'A lány a könyvtárban olvas.',
        english: 'The girl is reading in the library.',
        focus: 'Study scene',
      },
      {
        hungarian: 'A tanár az iskolában dolgozik.',
        english: 'The teacher works in the school.',
        focus: 'Work location',
      },
    ],
    practiceSets: [
      {
        id: 'location-fill',
        type: 'fill',
        title: 'Choose the location form',
        instructions:
          'Pick the correct ending or full place form to complete the sentence.',
        questions: [
          {
            id: 'l1',
            prompt: 'Say that the student is in the classroom.',
            template: 'A diák a ___ tanul.',
            choices: ['teremben', 'teremből', 'teremre'],
            answer: 'teremben',
            note: 'The sentence needs the "in" form here.',
          },
          {
            id: 'l2',
            prompt: 'Choose the right suffix for ház.',
            template: 'A nő a ház___ olvas.',
            choices: ['ban', 'ben', 'ből'],
            answer: 'ban',
            note: 'The full form is házban.',
          },
          {
            id: 'l3',
            prompt: 'Complete the place phrase.',
            template: 'A férfi az ___ ül.',
            choices: ['étteremben', 'étteremig', 'étteremre'],
            answer: 'étteremben',
            note: 'Again, the sentence asks for location inside a place.',
          },
          {
            id: 'l4',
            prompt: 'Say that the girl reads in the library.',
            template: 'A lány a ___ olvas.',
            choices: ['könyvtárban', 'könyvtárból', 'könyvtárra'],
            answer: 'könyvtárban',
            note: 'Store the whole chunk a könyvtárban.',
          },
          {
            id: 'l5',
            prompt: 'Choose the café location form.',
            template: 'A barátom a ___ vár.',
            choices: ['kávézóban', 'kávézóból', 'kávézóra'],
            answer: 'kávézóban',
            note: 'This is a useful meeting-place sentence frame.',
          },
          {
            id: 'l6',
            prompt: 'Say that the teacher works in the school.',
            template: 'A tanár az ___ dolgozik.',
            choices: ['iskolában', 'iskolából', 'iskolára'],
            answer: 'iskolában',
            note: 'Use the location form because the action happens there.',
          },
        ],
      },
      {
        id: 'location-match',
        type: 'match',
        title: 'Match place forms to meaning',
        instructions:
          'Practice ready-made location chunks by matching them directly to English.',
        pairs: [
          { left: 'teremben', right: 'in the classroom' },
          { left: 'házban', right: 'in the house' },
          { left: 'parkban', right: 'in the park' },
          { left: 'boltban', right: 'in the shop' },
          { left: 'étteremben', right: 'in the restaurant' },
          { left: 'könyvtárban', right: 'in the library' },
          { left: 'iskolában', right: 'in the school' },
          { left: 'kávézóban', right: 'in the café' },
        ],
      },
      createFlashcardPracticeSet({
        id: 'location-scenario-flashcards',
        title: 'Scenario flashcards for daily locations',
        instructions:
          'Read the scene and produce the Hungarian location sentence before you flip the card.',
        cards: buildScenarioFlashcardCards([
          {
            scenario: 'The student is studying in the classroom.',
            answer: 'A diák a teremben tanul.',
          },
          {
            scenario: 'The woman is shopping in the shop.',
            answer: 'A nő a boltban vásárol.',
          },
          {
            scenario: 'The man is sitting in the restaurant.',
            answer: 'A férfi az étteremben ül.',
          },
          {
            scenario: 'The girl is reading in the library.',
            answer: 'A lány a könyvtárban olvas.',
          },
          {
            scenario: 'The teacher works in the school.',
            answer: 'A tanár az iskolában dolgozik.',
          },
          {
            scenario: 'My friend is waiting in the café.',
            answer: 'A barátom a kávézóban vár.',
          },
        ]),
        sessionSize: 6,
        frontLabel: 'Scene',
        backLabel: 'Hungarian sentence',
      }),
    ],
  },
  {
    id: 'spatial-relations-scenes',
    trackId: 'core-grammar',
    topics: ['location', 'descriptions'],
    level: 'A1-A2',
    title: 'Spatial Relations in Real Scenes',
    subtitle: 'Use alatt, fölött, mellett, előtt, mögött, and között in everyday descriptions.',
    summary:
      'This lesson turns common postpositions into concrete scenes. Instead of memorizing under, above, and beside as a list, you practice how objects and places move around the same room, street, and home situations.',
    sourceUnits: ['Practical location extension'],
    goals: [
      'Answer Hol van? with common spatial relations.',
      'Contrast similar scene descriptions such as under vs beside and in front of vs behind.',
      'Describe object positions in rooms, streets, and picture-style scenes.',
      'Use van as a stable anchor while the location phrase changes.',
    ],
    studyFlow: [
      'Pick one object pair such as táska and asztal, then cycle it through alatt, mellett, and fölött.',
      'Practice the same room twice with different object positions so the contrast becomes clear.',
      'Say Hol van a... ? out loud before answering with the full scene sentence.',
      'Keep the whole chunk together: az asztal alatt, a ház előtt, az autó mögött.',
      'Return to these scenes later and swap in new nouns without changing the core pattern.',
    ],
    explanations: [
      {
        title: 'Postpositions work best as chunks',
        body:
          'At beginner level it is faster to learn az asztal alatt and a ház előtt as whole phrases than to memorize a translation list and build from zero each time.',
      },
      {
        title: 'Hol van? is the key question',
        body:
          'Most of these scenes grow from one useful question: Hol van? Once that question is stable, the answer pattern can repeat across many different objects.',
      },
      {
        title: 'Meaning comes from contrast',
        body:
          'Under, above, next to, in front of, and behind become clearer when the same object pair is reused. A táska az asztal alatt van feels different from A táska az asztal mellett van because only the location changes.',
      },
      {
        title: 'Use van as the anchor',
        body:
          'Most scene descriptions stay simple with van. That lets you focus on the location phrase itself instead of adding extra grammar at the same time.',
      },
    ],
    vocabulary: [
      { hungarian: 'az asztal alatt', english: 'under the table' },
      { hungarian: 'az asztal fölött', english: 'above the table' },
      { hungarian: 'az asztal mellett', english: 'next to the table' },
      { hungarian: 'a ház előtt', english: 'in front of the house' },
      { hungarian: 'az autó mögött', english: 'behind the car' },
      { hungarian: 'a két fa között', english: 'between the two trees' },
      { hungarian: 'az ágy alatt', english: 'under the bed' },
      { hungarian: 'a könyv mellett', english: 'next to the book' },
    ],
    examples: [
      {
        hungarian: 'A táska az asztal alatt van.',
        english: 'The bag is under the table.',
        focus: 'Under',
      },
      {
        hungarian: 'A lámpa az asztal fölött van.',
        english: 'The lamp is above the table.',
        focus: 'Above',
      },
      {
        hungarian: 'A szék az asztal mellett van.',
        english: 'The chair is next to the table.',
        focus: 'Beside',
      },
      {
        hungarian: 'A taxi a ház előtt van.',
        english: 'The taxi is in front of the house.',
        focus: 'In front of',
      },
      {
        hungarian: 'A bicikli az autó mögött van.',
        english: 'The bicycle is behind the car.',
        focus: 'Behind',
      },
      {
        hungarian: 'A pad a két fa között van.',
        english: 'The bench is between the two trees.',
        focus: 'Between',
      },
      {
        hungarian: 'A telefon a könyv mellett van.',
        english: 'The phone is next to the book.',
        focus: 'Desk scene',
      },
      {
        hungarian: 'Hol van a macska? Az ágy alatt van.',
        english: 'Where is the cat? It is under the bed.',
        focus: 'Question + answer',
      },
    ],
    practiceSets: [
      {
        id: 'spatial-fill',
        type: 'fill',
        title: 'Choose the spatial relation',
        instructions:
          'Pick the relation that matches the scene description best.',
        questions: [
          {
            id: 's1',
            prompt: 'The bag is under the chair.',
            template: 'A táska a szék ___ van.',
            choices: ['alatt', 'fölött', 'mellett'],
            answer: 'alatt',
            note: 'Use alatt for under.',
          },
          {
            id: 's2',
            prompt: 'The lamp is above the table.',
            template: 'A lámpa az asztal ___ van.',
            choices: ['fölött', 'alatt', 'mögött'],
            answer: 'fölött',
            note: 'Use fölött for above.',
          },
          {
            id: 's3',
            prompt: 'The chair is next to the table.',
            template: 'A szék az asztal ___ van.',
            choices: ['mellett', 'előtt', 'között'],
            answer: 'mellett',
            note: 'Mellett means beside or next to.',
          },
          {
            id: 's4',
            prompt: 'The taxi is in front of the house.',
            template: 'A taxi a ház ___ van.',
            choices: ['előtt', 'mögött', 'alatt'],
            answer: 'előtt',
            note: 'Előtt means in front of.',
          },
          {
            id: 's5',
            prompt: 'The bicycle is behind the car.',
            template: 'A bicikli az autó ___ van.',
            choices: ['mögött', 'mellett', 'fölött'],
            answer: 'mögött',
            note: 'Mögött means behind.',
          },
          {
            id: 's6',
            prompt: 'The bench is between the two trees.',
            template: 'A pad a két fa ___ van.',
            choices: ['között', 'előtt', 'alatt'],
            answer: 'között',
            note: 'Között is the between relation.',
          },
          {
            id: 's7',
            prompt: 'The cat is under the bed.',
            template: 'A macska az ágy ___ van.',
            choices: ['alatt', 'mellett', 'fölött'],
            answer: 'alatt',
            note: 'This is a common house scene.',
          },
          {
            id: 's8',
            prompt: 'The picture is above the sofa.',
            template: 'A kép a kanapé ___ van.',
            choices: ['fölött', 'mögött', 'között'],
            answer: 'fölött',
            note: 'Think of wall decoration in a room.',
          },
        ],
      },
      {
        id: 'spatial-scene-fill',
        type: 'fill',
        title: 'Keep the same scene but change the position',
        instructions:
          'These prompts reuse similar rooms and objects so you can feel the difference between the relations.',
        questions: [
          {
            id: 'ss1',
            prompt: 'In the office, the printer is next to the desk.',
            template: 'Az irodában a nyomtató az íróasztal ___ van.',
            choices: ['mellett', 'alatt', 'mögött'],
            answer: 'mellett',
            note: 'Same office scene, different possible positions.',
          },
          {
            id: 'ss2',
            prompt: 'In the bedroom, the shoes are under the bed.',
            template: 'A hálószobában a cipők az ágy ___ vannak.',
            choices: ['alatt', 'előtt', 'fölött'],
            answer: 'alatt',
            note: 'Keep the room image in mind while choosing.',
          },
          {
            id: 'ss3',
            prompt: 'In the street, the bus stop is in front of the pharmacy.',
            template: 'Az utcán a buszmegálló a gyógyszertár ___ van.',
            choices: ['előtt', 'mögött', 'között'],
            answer: 'előtt',
            note: 'Street navigation scenes make these forms more practical.',
          },
          {
            id: 'ss4',
            prompt: 'In the park, the child is between the benches.',
            template: 'A parkban a gyerek a padok ___ van.',
            choices: ['között', 'mellett', 'fölött'],
            answer: 'között',
            note: 'Use the between relation when something is framed by two similar things.',
          },
          {
            id: 'ss5',
            prompt: 'In the kitchen, the clock is above the door.',
            template: 'A konyhában az óra az ajtó ___ van.',
            choices: ['fölött', 'alatt', 'mögött'],
            answer: 'fölött',
            note: 'This is another indoor visual scene.',
          },
          {
            id: 'ss6',
            prompt: 'In the garage, the bike is behind the car.',
            template: 'A garázsban a bicikli az autó ___ van.',
            choices: ['mögött', 'mellett', 'előtt'],
            answer: 'mögött',
            note: 'Behind and beside are easy to confuse unless you reuse the same scene.',
          },
        ],
      },
      {
        id: 'spatial-match',
        type: 'match',
        title: 'Match the spatial chunk to its meaning',
        instructions:
          'Match the full Hungarian chunk to the English meaning or scene role.',
        pairs: [
          { left: 'az asztal alatt', right: 'under the table' },
          { left: 'az asztal fölött', right: 'above the table' },
          { left: 'az asztal mellett', right: 'next to the table' },
          { left: 'a ház előtt', right: 'in front of the house' },
          { left: 'az autó mögött', right: 'behind the car' },
          { left: 'a két fa között', right: 'between the two trees' },
          { left: 'az ágy alatt', right: 'under the bed' },
          { left: 'a könyv mellett', right: 'next to the book' },
        ],
      },
      createFlashcardPracticeSet({
        id: 'spatial-scenario-flashcards',
        title: 'Scenario flashcards for object positions',
        instructions:
          'Read the scene, picture it clearly, and say the Hungarian sentence before you flip the card.',
        cards: buildScenarioFlashcardCards([
          {
            scenario: 'The bag is under the table.',
            answer: 'A táska az asztal alatt van.',
          },
          {
            scenario: 'The lamp is above the table.',
            answer: 'A lámpa az asztal fölött van.',
          },
          {
            scenario: 'The chair is next to the table.',
            answer: 'A szék az asztal mellett van.',
          },
          {
            scenario: 'The taxi is in front of the house.',
            answer: 'A taxi a ház előtt van.',
          },
          {
            scenario: 'The bicycle is behind the car.',
            answer: 'A bicikli az autó mögött van.',
          },
          {
            scenario: 'The bench is between the two trees.',
            answer: 'A pad a két fa között van.',
          },
          {
            scenario: 'The phone is next to the book.',
            answer: 'A telefon a könyv mellett van.',
          },
          {
            scenario: 'The cat is under the bed.',
            answer: 'A macska az ágy alatt van.',
          },
        ]),
        sessionSize: 8,
        frontLabel: 'Scene',
        backLabel: 'Hungarian sentence',
      }),
    ],
  },
  {
    id: 'present-tense-verb-patterns',
    trackId: 'core-grammar',
    topics: ['present', 'verbs', 'routine'],
    level: 'A1-A2',
    title: 'Present Tense Verb Patterns',
    subtitle: 'Turn a compact summary table into natural everyday conjugation.',
    summary:
      'This lesson turns a handwritten-style Hungarian present-tense summary into a working speaking system. You will practice the default endings, s / sz / z stems, common -ik verbs, and the irregular anchors van, megy, and jön through routine, hobby, and movement scenes.',
    sourceUnits: ['Verb summary table', 'Present tense drill'],
    goals: [
      'Recognize the main indefinite present-tense patterns from a compact chart.',
      'Conjugate frequent verbs across all six persons without needing the subject pronoun every time.',
      'Use daily-life, hobby, and movement verbs in short natural scenes.',
      'Memorize the irregular anchor families vagyok, megyek, and jövök as whole units.',
    ],
    studyFlow: [
      'Work one pattern at a time: say the six-person family aloud before mixing verbs.',
      'Start with one anchor verb per pattern, then swap in new vocabulary from the same group.',
      'Keep the pronouns in the first round, then drop them in the second round so the ending carries the subject.',
      'Attach the verb to a real scene such as reggel, este, a parkban, or otthon instead of drilling bare forms only.',
      'If one verb still feels unstable, run a short loop: én, te, ő, mi, ti, ők.',
    ],
    explanations: [
      {
        title: 'Stay in one system first',
        body:
          'This lesson stays in the indefinite present. That is enough for a large amount of early real speech: Várok. Olvasunk. Találkoznak. You do not need the definite system at the same time while these endings are still new.',
        tips: [
          'Keep objects out of the sentence when you want to focus only on the present-tense ending.',
        ],
      },
      {
        title: 'Pattern 1: the default non -ik family',
        body:
          'Many common verbs follow the core ending set -k, -sz, zero, -unk or -ünk, -tok or -tek or -tök, -nak or -nek. Learn them as full sound families such as várok, vársz, vár, várunk, vártok, várnak.',
        tips: [
          'Good anchor verbs here are vár, fut, áll, ír, and pihen.',
        ],
      },
      {
        title: 'Pattern 2: stems ending in s, sz, or z',
        body:
          'These verbs often show a linking vowel in forms such as olvasol, nézel, főzöl, and mosol. The ti form also keeps that heavier stem shape: olvastok, néztek, főztök, mostok.',
        tips: [
          'Treat te and ti forms as ready-made chunks instead of trying to build them from a bare stem each time.',
        ],
      },
      {
        title: 'Pattern 3: common -ik verbs',
        body:
          'Your summary table is especially useful for high-frequency -ik verbs. In the standard learner pattern, many of them are easiest to store as -om or -em or -öm, -ol or -el or -öl, -ik, -unk or -ünk, -otok or -etek or -ötök, -nak or -nek: eszem, eszel, eszik; iszom, iszol, iszik; alszom, alszol, alszik.',
        tips: [
          'This lesson keeps the standard learner pattern even if you later hear some colloquial variants in speech.',
        ],
      },
      {
        title: 'Pattern 4: -ít verbs and heavy stems',
        body:
          'Verbs such as tanít and takarít, and also tight consonant stems such as fest, are easier when you memorize the whole sound shape: tanítok, tanítasz, tanít; takarítok, takarítasz, takarít; festek, festesz, fest.',
        tips: [
          'Do not over-separate the stem from the ending when the stem already feels crowded.',
        ],
      },
      {
        title: 'Memorize the irregular anchors whole',
        body:
          'Megy, jön, and van are worth learning as complete families instead of forcing them into a regular chart: megyek, mész, megy; jövök, jössz, jön; vagyok, vagy, van.',
        tips: [
          'Formal ön takes the same verb form as ő.',
        ],
      },
      {
        title: 'Natural speech usually drops the pronoun',
        body:
          'Once the ending is stable, Hungarian usually lets the verb show the subject. Say Reggel főzök or Este találkozunk instead of repeating én or mi every time. Add the pronoun only when you want contrast or emphasis.',
        tips: [
          'Do one round with explicit pronouns, then one round without them.',
        ],
      },
    ],
    vocabulary: [
      { hungarian: 'fürdik', english: 'bathes / takes a bath', note: '-ik' },
      { hungarian: 'vesz', english: 'buys / takes', note: 's / sz / z stem' },
      { hungarian: 'takarít', english: 'cleans / tidies', note: '-ít' },
      { hungarian: 'jön', english: 'comes', note: 'irregular' },
      { hungarian: 'főz', english: 'cooks', note: 's / sz / z stem' },
      { hungarian: 'sír', english: 'cries', note: 'regular' },
      { hungarian: 'biciklizik', english: 'cycles', note: '-ik' },
      { hungarian: 'táncol', english: 'dances', note: 'regular' },
      { hungarian: 'iszik', english: 'drinks', note: '-ik' },
      { hungarian: 'vezet', english: 'drives', note: 'regular' },
      { hungarian: 'eszik', english: 'eats', note: '-ik' },
      { hungarian: 'horgászik', english: 'fishes', note: '-ik' },
      { hungarian: 'öltözik', english: 'gets dressed', note: '-ik' },
      { hungarian: 'megy', english: 'goes', note: 'irregular' },
      { hungarian: 'reggelizik', english: 'has breakfast', note: '-ik' },
      { hungarian: 'vacsorázik', english: 'has dinner', note: '-ik' },
      { hungarian: 'ebédel', english: 'has lunch', note: 'regular' },
      { hungarian: 'kirándul', english: 'goes hiking', note: 'regular' },
      { hungarian: 'siet', english: 'hurries', note: 'regular' },
      { hungarian: 'csókolózik', english: 'kisses', note: '-ik' },
      { hungarian: 'köt', english: 'knits / ties', note: 'regular' },
      { hungarian: 'nevet', english: 'laughs', note: 'regular' },
      { hungarian: 'hallgat', english: 'listens / stays quiet', note: 'regular' },
      { hungarian: 'találkozik', english: 'meets', note: '-ik' },
      { hungarian: 'fest', english: 'paints', note: 'heavy stem' },
      { hungarian: 'játszik', english: 'plays', note: '-ik' },
      { hungarian: 'kártyázik', english: 'plays cards', note: '-ik' },
      { hungarian: 'sakkozik', english: 'plays chess', note: '-ik' },
      { hungarian: 'focizik', english: 'plays football', note: '-ik' },
      { hungarian: 'gitározik', english: 'plays the guitar', note: '-ik' },
      { hungarian: 'zongorázik', english: 'plays the piano', note: '-ik' },
      { hungarian: 'teniszezik', english: 'plays tennis', note: '-ik' },
      { hungarian: 'olvas', english: 'reads', note: 's / sz / z stem' },
      { hungarian: 'pihen', english: 'rests', note: 'regular' },
      { hungarian: 'lovagol', english: 'rides a horse', note: 'regular' },
      { hungarian: 'fut', english: 'runs', note: 'regular' },
      { hungarian: 'borotválkozik', english: 'shaves', note: '-ik' },
      { hungarian: 'énekel', english: 'sings', note: 'regular' },
      { hungarian: 'síel', english: 'skis', note: 'regular' },
      { hungarian: 'alszik', english: 'sleeps', note: '-ik' },
      { hungarian: 'dohányzik', english: 'smokes', note: '-ik' },
      { hungarian: 'áll', english: 'stands', note: 'regular' },
      { hungarian: 'úszik', english: 'swims', note: '-ik' },
      { hungarian: 'fényképez', english: 'takes photos', note: 's / sz / z stem' },
      { hungarian: 'tanít', english: 'teaches', note: '-ít' },
      { hungarian: 'vár', english: 'waits', note: 'regular' },
      { hungarian: 'mos', english: 'washes', note: 's / sz / z stem' },
      { hungarian: 'mosogat', english: 'washes dishes', note: 'regular' },
      { hungarian: 'néz', english: 'watches / looks', note: 's / sz / z stem' },
      { hungarian: 'dolgozik', english: 'works', note: '-ik' },
      { hungarian: 'ír', english: 'writes', note: 'regular' },
      { hungarian: 'van', english: 'is / there is', note: 'irregular anchor' },
    ],
    examples: [
      {
        hungarian: 'Reggel várok a buszra.',
        english: 'In the morning I wait for the bus.',
        focus: 'Default pattern',
      },
      {
        hungarian: 'Este olvasol vagy főzöl?',
        english: 'In the evening do you read or cook?',
        focus: 's / sz / z stems',
      },
      {
        hungarian: 'Most eszem, te pedig iszol.',
        english: 'I am eating now, and you are drinking.',
        focus: '-ik verbs',
      },
      {
        hungarian: 'A gyerek alszik, a szülők pedig pihennek.',
        english: 'The child is sleeping, and the parents are resting.',
        focus: 'Third-person scene',
      },
      {
        hungarian: 'A barátok a parkban találkoznak.',
        english: 'The friends meet in the park.',
        focus: 'Real scene with an -ik verb',
      },
      {
        hungarian: 'Ma dolgozom, de este kirándulok.',
        english: 'Today I work, but in the evening I go hiking.',
        focus: 'Two first-person actions',
      },
      {
        hungarian: 'Holnap Budapestre megyünk, és korán jövünk haza.',
        english: 'Tomorrow we are going to Budapest, and we are coming home early.',
        focus: 'Irregular anchors',
      },
      {
        hungarian: 'A fiú gitározik, a lány zongorázik.',
        english: 'The boy plays guitar, and the girl plays piano.',
        focus: 'Activity verbs in context',
      },
      {
        hungarian: 'Mi gyorsan takarítunk, ti pedig mostok.',
        english: 'We clean quickly, and you all wash.',
        focus: '-ít plus s-stem contrast',
      },
      {
        hungarian: 'A tanár tanít, a diákok hallgatnak és írnak.',
        english: 'The teacher teaches, and the students listen and write.',
        focus: 'Natural classroom scene',
      },
    ],
    practiceSets: [
      {
        id: 'verb-patterns-regular-fill',
        type: 'fill',
        title: 'Choose the regular present-tense form',
        instructions:
          'Complete the sentence with the form that fits the subject and keeps the verb in the indefinite present.',
        questions: [
          {
            id: 'vpr1',
            prompt: 'Say: I wait for the bus every morning.',
            template: 'Minden reggel a buszra ___ .',
            choices: ['várok', 'vársz', 'várnak'],
            answer: 'várok',
            note: 'This is the basic first-person singular pattern: várok.',
          },
          {
            id: 'vpr2',
            prompt: 'Say: you write a lot today.',
            template: 'Ma sokat ___ .',
            choices: ['írsz', 'írok', 'írnak'],
            answer: 'írsz',
            note: 'Te usually pushes the clear -sz ending in this regular family.',
          },
          {
            id: 'vpr3',
            prompt: 'Say: he or she cleans in the afternoon.',
            template: 'Délután ___ .',
            choices: ['takarít', 'takarítok', 'takarítunk'],
            answer: 'takarít',
            note: 'Third-person singular is often the bare dictionary form.',
          },
          {
            id: 'vpr4',
            prompt: 'Say: we run in the park.',
            template: 'A parkban ___ .',
            choices: ['futunk', 'futtok', 'futnak'],
            answer: 'futunk',
            note: 'Mi takes the -unk or -ünk ending.',
          },
          {
            id: 'vpr5',
            prompt: 'Say: you all stand at the door.',
            template: 'Az ajtóban ___ .',
            choices: ['álltok', 'állunk', 'állnak'],
            answer: 'álltok',
            note: 'Ti needs the second-person plural ending.',
          },
          {
            id: 'vpr6',
            prompt: 'Say: they sing beautifully.',
            template: 'Szépen ___ .',
            choices: ['énekelnek', 'énekelsz', 'énekelek'],
            answer: 'énekelnek',
            note: 'Ők takes -nak or -nek depending on vowel harmony.',
          },
          {
            id: 'vpr7',
            prompt: 'Say: the teacher teaches well.',
            template: 'A tanár jól ___ .',
            choices: ['tanít', 'tanítasz', 'tanítanak'],
            answer: 'tanít',
            note: 'This keeps the third-person singular anchor form.',
          },
          {
            id: 'vpr8',
            prompt: 'Say: we paint quickly, then we rest.',
            template: 'Gyorsan ___, aztán pihenünk.',
            choices: ['festünk', 'festetek', 'festenek'],
            answer: 'festünk',
            note: 'Fest is easier when memorized as a full sound shape: festek, festesz, fest.',
          },
        ],
      },
      {
        id: 'verb-patterns-s-stem-fill',
        type: 'fill',
        title: 'Choose the s / sz / z stem form',
        instructions:
          'These verbs often need a linking vowel. Pick the form that sounds natural with the subject.',
        questions: [
          {
            id: 'vps1',
            prompt: 'Say: you read a lot in the evening.',
            template: 'Este sokat ___ .',
            choices: ['olvasol', 'olvasok', 'olvasnak'],
            answer: 'olvasol',
            note: 'The te form is a ready-made chunk here: olvasol.',
          },
          {
            id: 'vps2',
            prompt: 'Say: you all watch a film.',
            template: 'Filmet ___ .',
            choices: ['néztek', 'nézel', 'nézünk'],
            answer: 'néztek',
            note: 'Ti gives you the plural form néztek.',
          },
          {
            id: 'vps3',
            prompt: 'Say: you cook well.',
            template: 'Jól ___ .',
            choices: ['főzöl', 'főzök', 'főznek'],
            answer: 'főzöl',
            note: 'The te form keeps the linking vowel: főzöl.',
          },
          {
            id: 'vps4',
            prompt: 'Say: they wash before dinner.',
            template: 'Vacsora előtt ___ .',
            choices: ['mosnak', 'mosol', 'mosunk'],
            answer: 'mosnak',
            note: 'Here the subject is ők, so use the third-person plural.',
          },
          {
            id: 'vps5',
            prompt: 'Say: you buy bread in the shop.',
            template: 'A boltban kenyeret ___ .',
            choices: ['veszel', 'veszek', 'vesz'],
            answer: 'veszel',
            note: 'Vesz is high-frequency, so the te form veszel is worth overlearning.',
          },
          {
            id: 'vps6',
            prompt: 'Say: I take photos on the trip.',
            template: 'A kiránduláson ___ .',
            choices: ['fényképezek', 'fényképezel', 'fényképez'],
            answer: 'fényképezek',
            note: 'This keeps the first-person singular pattern in a long z-stem verb.',
          },
          {
            id: 'vps7',
            prompt: 'Say: we are reading now.',
            template: 'Most ___ .',
            choices: ['olvasunk', 'olvastok', 'olvasnak'],
            answer: 'olvasunk',
            note: 'Mi needs the first-person plural ending.',
          },
          {
            id: 'vps8',
            prompt: 'Say: they are watching a picture now.',
            template: 'Most egy képet ___ .',
            choices: ['néznek', 'nézel', 'nézünk'],
            answer: 'néznek',
            note: 'Keep the verb in the indefinite present: néznek.',
          },
        ],
      },
      {
        id: 'verb-patterns-ik-fill',
        type: 'fill',
        title: 'Choose the common -ik form',
        instructions:
          'Use the standard learner pattern from the summary table for these high-frequency -ik verbs.',
        questions: [
          {
            id: 'vpi1',
            prompt: 'Say: I am drinking water now.',
            template: 'Most vizet ___ .',
            choices: ['iszom', 'iszol', 'iszik'],
            answer: 'iszom',
            note: 'Store iszom, iszol, iszik as a compact family.',
          },
          {
            id: 'vpi2',
            prompt: 'Say: you sleep a lot at the weekend.',
            template: 'Hétvégén sokat ___ .',
            choices: ['alszol', 'alszom', 'alszanak'],
            answer: 'alszol',
            note: 'This keeps the standard learner form alszol.',
          },
          {
            id: 'vpi3',
            prompt: 'Say: he or she eats early.',
            template: 'Korán ___ .',
            choices: ['eszik', 'eszem', 'eszünk'],
            answer: 'eszik',
            note: 'Third-person singular stays in the base form eszik.',
          },
          {
            id: 'vpi4',
            prompt: 'Say: we meet in the park.',
            template: 'A parkban ___ .',
            choices: ['találkozunk', 'találkoztok', 'találkoznak'],
            answer: 'találkozunk',
            note: 'Találkozik becomes találkozunk with mi.',
          },
          {
            id: 'vpi5',
            prompt: 'Say: I work at home today.',
            template: 'Ma otthon ___ .',
            choices: ['dolgozom', 'dolgozol', 'dolgozik'],
            answer: 'dolgozom',
            note: 'Dolgozom is one of the most useful first-person forms in daily speech.',
          },
          {
            id: 'vpi6',
            prompt: 'Say: the child gets dressed quickly.',
            template: 'A gyerek gyorsan ___ .',
            choices: ['öltözik', 'öltözöm', 'öltözünk'],
            answer: 'öltözik',
            note: 'Keep the scene simple and let the third-person form do the work.',
          },
          {
            id: 'vpi7',
            prompt: 'Say: they swim in the lake in summer.',
            template: 'Nyáron a tóban ___ .',
            choices: ['úsznak', 'úszunk', 'úszol'],
            answer: 'úsznak',
            note: 'Ők needs the plural form: úsznak.',
          },
          {
            id: 'vpi8',
            prompt: 'Say: we have dinner together.',
            template: 'Együtt ___ .',
            choices: ['vacsorázunk', 'vacsoráztok', 'vacsoráznak'],
            answer: 'vacsorázunk',
            note: 'Treat routine verbs like reggelizik and vacsorázik as daily chunks.',
          },
        ],
      },
      {
        id: 'verb-patterns-irregular-fill',
        type: 'fill',
        title: 'Memorize the irregular anchors',
        instructions:
          'These forms are worth knowing cold. Choose the form that fits the person and the scene.',
        questions: [
          {
            id: 'vpm1',
            prompt: 'Say: I am going home now.',
            template: 'Most haza ___ .',
            choices: ['megyek', 'mész', 'megy'],
            answer: 'megyek',
            note: 'This verb is irregular, so store the whole form megyek.',
          },
          {
            id: 'vpm2',
            prompt: 'Say: are you coming early today?',
            template: 'Ma korán ___ ?',
            choices: ['jössz', 'jövök', 'jön'],
            answer: 'jössz',
            note: 'The te form is jössz, not a regular *jönsz.',
          },
          {
            id: 'vpm3',
            prompt: 'Say: we are already in the café.',
            template: 'Már a kávézóban ___ .',
            choices: ['vagyunk', 'vannak', 'vagytok'],
            answer: 'vagyunk',
            note: 'Van is another family that must be learned whole.',
          },
          {
            id: 'vpm4',
            prompt: 'Say: they go by bus every day.',
            template: 'Minden nap busszal ___ .',
            choices: ['mennek', 'megyünk', 'mész'],
            answer: 'mennek',
            note: 'The plural family is mennek, not megynek.',
          },
          {
            id: 'vpm5',
            prompt: 'Say this politely to one person: are you coming early today?',
            template: 'Ön ma korán ___ ?',
            choices: ['jön', 'jössz', 'jövök'],
            answer: 'jön',
            note: 'Ön uses the same verb form as ő.',
          },
          {
            id: 'vpm6',
            prompt: 'Say: the book is on the table.',
            template: 'A könyv az asztalon ___ .',
            choices: ['van', 'vagyok', 'vannak'],
            answer: 'van',
            note: 'This is a high-value location anchor.',
          },
          {
            id: 'vpm7',
            prompt: 'Say: you all are already on the way.',
            template: 'Már úton ___ .',
            choices: ['vagytok', 'vagyunk', 'vannak'],
            answer: 'vagytok',
            note: 'Keep the plural family together: vagyunk, vagytok, vannak.',
          },
          {
            id: 'vpm8',
            prompt: 'Say: tomorrow we are going to Budapest.',
            template: 'Holnap Budapestre ___ .',
            choices: ['megyünk', 'mennek', 'mész'],
            answer: 'megyünk',
            note: 'Mi takes the memorized irregular plural form megyünk.',
          },
        ],
      },
      {
        id: 'verb-patterns-scene-fill',
        type: 'fill',
        title: 'Pick the verb that fits the scene',
        instructions:
          'Now focus less on the ending chart and more on choosing a natural verb for the situation.',
        questions: [
          {
            id: 'vpsf1',
            prompt: 'Say that the grandfather is fishing.',
            template: 'A nagypapa ___ .',
            choices: ['horgászik', 'táncol', 'borotválkozik'],
            answer: 'horgászik',
            note: 'Use scene meaning, not just ending recognition.',
          },
          {
            id: 'vpsf2',
            prompt: 'Say that the child is crying.',
            template: 'A gyerek ___ .',
            choices: ['sír', 'vezet', 'fest'],
            answer: 'sír',
            note: 'Keep the sentence short and natural.',
          },
          {
            id: 'vpsf3',
            prompt: 'Say that I wash the dishes in the evening.',
            template: 'Este ___ .',
            choices: ['mosogatok', 'lovagolok', 'csókolózom'],
            answer: 'mosogatok',
            note: 'Attach the verb to a familiar routine scene.',
          },
          {
            id: 'vpsf4',
            prompt: 'Say that the friends are playing chess.',
            template: 'A barátok ___ .',
            choices: ['sakkoznak', 'ebédelnek', 'futnak'],
            answer: 'sakkoznak',
            note: 'This pulls hobby vocabulary into a full sentence.',
          },
          {
            id: 'vpsf5',
            prompt: 'Say that the boy is playing the guitar.',
            template: 'A fiú ___ .',
            choices: ['gitározik', 'dohányzik', 'siet'],
            answer: 'gitározik',
            note: 'Third-person singular lets you focus on meaning without extra grammar.',
          },
          {
            id: 'vpsf6',
            prompt: 'Say that we are taking photos during the trip.',
            template: 'Kirándulás közben ___ .',
            choices: ['fényképezünk', 'kötünk', 'mosunk'],
            answer: 'fényképezünk',
            note: 'This reuses a long z-stem form in a real travel scene.',
          },
          {
            id: 'vpsf7',
            prompt: 'Say that the woman is dancing.',
            template: 'A nő ___ .',
            choices: ['táncol', 'vezet', 'főz'],
            answer: 'táncol',
            note: 'Choose the verb by scene meaning first.',
          },
          {
            id: 'vpsf8',
            prompt: 'Say that the children play football on Saturday.',
            template: 'Szombaton a gyerekek ___ .',
            choices: ['fociznak', 'reggeliznek', 'hallgatnak'],
            answer: 'fociznak',
            note: 'This brings the sports verbs into a reusable weekend frame.',
          },
        ],
      },
      {
        id: 'verb-patterns-match',
        type: 'match',
        title: 'Match conjugated forms to meaning',
        instructions:
          'Pair the full conjugated verb with the person and meaning it expresses.',
        pairs: [
          { left: 'várok', right: 'I wait' },
          { left: 'olvasol', right: 'you read' },
          { left: 'főzünk', right: 'we cook' },
          { left: 'néztek', right: 'you all watch' },
          { left: 'eszem', right: 'I eat' },
          { left: 'iszol', right: 'you drink' },
          { left: 'dolgozom', right: 'I work' },
          { left: 'találkozunk', right: 'we meet' },
          { left: 'jövök', right: 'I come' },
          { left: 'mennek', right: 'they go' },
        ],
      },
      createFlashcardPracticeSet({
        id: 'verb-patterns-scenario-flashcards',
        title: 'Scenario flashcards for natural verb use',
        instructions:
          'Read the scene prompt, say the Hungarian sentence aloud, then flip the card and check the full answer.',
        cards: buildScenarioFlashcardCards([
          {
            scenario: 'You say: I am waiting for the bus.',
            answer: 'Várok a buszra.',
          },
          {
            scenario: 'You say: We are reading at home.',
            answer: 'Otthon olvasunk.',
          },
          {
            scenario: 'You say: The man is cooking.',
            answer: 'A férfi főz.',
          },
          {
            scenario: 'You say: They are cycling in the city.',
            answer: 'A városban bicikliznek.',
          },
          {
            scenario: 'You say: The girl sings and dances.',
            answer: 'A lány énekel és táncol.',
          },
          {
            scenario: 'You say: We meet in the park.',
            answer: 'A parkban találkozunk.',
          },
          {
            scenario: 'You say: Today I work, but in the evening I rest.',
            answer: 'Ma dolgozom, de este pihenek.',
          },
          {
            scenario: 'You say: The child is sleeping.',
            answer: 'A gyerek alszik.',
          },
          {
            scenario: 'You say: Tomorrow we are going to Budapest.',
            answer: 'Holnap Budapestre megyünk.',
          },
          {
            scenario: 'You say: I am coming now.',
            answer: 'Most jövök.',
          },
          {
            scenario: 'You say: The boy plays guitar, and the girl plays piano.',
            answer: 'A fiú gitározik, a lány zongorázik.',
          },
          {
            scenario: 'You say: We take photos and hike.',
            answer: 'Fényképezünk és kirándulunk.',
          },
          {
            scenario: 'You say: The teacher teaches, and the students listen and write.',
            answer: 'A tanár tanít, a diákok hallgatnak és írnak.',
          },
          {
            scenario: 'You say: In the evening the friends play cards.',
            answer: 'Este a barátok kártyáznak.',
          },
          {
            scenario: 'You say: On Saturday they play tennis.',
            answer: 'Szombaton teniszeznek.',
          },
          {
            scenario: 'You say: The old man shaves quickly.',
            answer: 'Az öregúr gyorsan borotválkozik.',
          },
          {
            scenario: 'You say: They laugh a lot.',
            answer: 'Sokat nevetnek.',
          },
          {
            scenario: 'You say: The man drives carefully.',
            answer: 'A férfi óvatosan vezet.',
          },
          {
            scenario: 'You say: We swim in the lake.',
            answer: 'A tóban úszunk.',
          },
          {
            scenario: 'You say: In the kitchen I wash dishes, then I clean.',
            answer: 'A konyhában mosogatok, aztán takarítok.',
          },
        ]),
        sessionSize: 12,
        frontLabel: 'Scene',
        backLabel: 'Hungarian sentence',
      }),
    ],
  },
]
